### ISSUE TITLE
Not finished ACRE implementation

### ISSUE THREAD

**Issue by JustAKuba** [Project-Hatchet/public_h-60#110]
# Prerequisites

# Bug Report

## **Description:**
UH have working implemented ACRE radio rack feature, but physical panel on lower mid panel with purpose to controle those dont work

### **Expected Behavior**
The active channel and its volume should change as user interacts with control knobs on lower mid panel.

### **Additional context**
This matter was discussed on official discord
https://discord.com/channels/487939925938012161/811721869480820749/818498653521051728

**Comment by BroBeansCPG** [comment]
volume knobs and ICS work as intended on RC0.3.1

TX ICS knob has no affect as far as I can tell
