### ISSUE TITLE
~2 InterCom ports for passengers

### ISSUE THREAD

**Issue by BroBeansCPG** [Project-Hatchet/public_h-60#118]
## **Is your feature request related to a problem? Please describe.**

I believe intercom should be available for 
a) Hoist Operator and/or
b) PJs and/or
c) Squadleader

## **Describe the solution you'd like**

At least 1 or 2 intercom slots added for the cargo slots, whether it's count how many users are connected or just limit it to the front most FFV spots/Hoist operator

## **Describe alternatives you've considered**

Radio usage, but messy

## **Additional context**

Is IC even available to cargo in real life? I'm not sure, I know guys aren't taking their helmets off to change headset, but is there like a jack they can connect to their existing comms set up to tap in?
I'd imagine it's pretty uncommon for regular cargo guys to tap in, but I can imagine PJ's having comms is pretty important. Maybe they just use short range radio

Still wouldn't mind seeing it considered for a gameplay mechanic

**Comment by ampersand38** [comment]
Is this for ACRE or TFAR or what? I know in TFAR Beta everyone has access to all the intercom channels.

**Comment by YannikH** [comment]
In real life there is a single jack in the back for the troop commander to jack their own headset in to. I'd imagine that HH-60s have additional points in the back though. It's a good thing to add. I think the UH-60M already has it set up properly, but since the seat is classed as a normal cargo seat there's no way to get in to the specific one, so we'd have to convert it to a named cargo turret.

**Comment by BroBeansCPG** [comment]
> Is this for ACRE or TFAR or what? I know in TFAR Beta everyone has access to all the intercom channels.

ACRE

I know RHS doesn’t have intercom available for FFV seats, is that a limitation or just laziness?

**Comment by sevn10** [comment]
+1 This would be extremely nice to have in the DAP or slicks. To my knowledge the UH and MH have jack panels for headsets on either side of the cabin and in front of and behind the cabin doors. The crew chief spot just has additional controls for intercoms and radios.
