### ISSUE TITLE
Bug: Hellfires not aligned with Pylons

### ISSUE THREAD

**Issue by BroBeansCPG** [Project-Hatchet/public_h-60#119]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

Can add later if required

# Bug Report

## **Description:**

VTX Hellfires are x meters below the pylon, appearing underground while on the ground

Note: Pylon is correctly attached to pylon position. Physical missiles are not on their rack. See images.  

### **Expected Behavior**

Hellfires should be attached to pylon mounts

### Steps to Reproduce the Issue

Spawn Dap
Check pylons have VTX Hellfires on
Result (Maybe)

### **Screenshots**

![img](https://cdn.discordapp.com/attachments/673726626915287080/821325567222874132/20210316193552_1.jpg)

### **Video**

N/A

### **Additional context**

Mods running CBA, ACE, Hatchet, H60RC3.1.0, RHSUSAF, ZeusEnhanced

Needs reproducing with minimum mods..

**Comment by ampersand38** [comment]
fixed in 3.1.2
