### ISSUE TITLE
Bug: Copilot loses Laser if he controls any weapons

### ISSUE THREAD

**Issue by vincione** [Project-Hatchet/public_h-60#121]
If the chopper is set up with weapons controlled by copilot the Laser is lost by the copilot. By that it means  the cross disappears and the weapon don't follow the laser, even if the pilot can see it active.

**Comment by vincione** [comment]
Tested on RC 0.3.1

**Comment by BroBeansCPG** [comment]
@vincione is #126 the same issue that you had occurring?

**Comment by vincione** [comment]
yes should be the same

**Comment by vincione** [comment]
I recently retried to reproduce. As the copilot with the control of weapons: 
1/ impossible to fire while in flir camera
2/ It's possible to fire while outside camera but the triangle gets down 30 cm below and stops to move. Where ever you look with the camera, when you get ouside it just gets straight down.  
3/ the cross laser around the triangle disapparears, but: All AGM-114K (M299) or H60 or ACE variants follow the laser that is still active. DAGR laser guided missile doesn't follow though.

**Comment by ampersand38** [comment]
FIxed in 0.4.0
