### ISSUE TITLE
Bug: Front wheels are too strong

### ISSUE THREAD

**Issue by allegedflora** [Project-Hatchet/public_h-60#122]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**
Will add if needed

# Bug Report

## **Description:**

Front wheels are a bit too strong, When landing, they can suspend the helicopter on only themselves, leading to intresting results

### **Expected Behavior**

Front wheels collapse under the weight, bringing the helicopter into a flat state

### Steps to Reproduce the Issue
1. Land H-60 with nose pointed slightly down on the front wheels
2. Profit

### **Screenshots**

![20210321005413_1](https://user-images.githubusercontent.com/37432237/111898270-e45dc500-8a1c-11eb-9955-4239a1b94c51.jpg)

**Comment by ampersand38** [comment]
The CG is too far forward.
![image](https://user-images.githubusercontent.com/11483210/146215195-9c1999c8-4b0d-4056-bbb1-1aedf25c4fa3.png)

**Comment by FatLurch** [comment]
I believe this is resolved and can be closed.
