### ISSUE TITLE
Bug: Running into the UH-60 can cause the helicopter to tip and explode when using AFM

### ISSUE THREAD

**Issue by allegedflora** [Project-Hatchet/public_h-60#123]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**
Gone at this point unfortunatly
# Bug Report

## **Description:**

Sometimes when a pilot is on the ground using AFM, if somebody runs into the side of the aircraft, it will tip and explode

### **Expected Behavior**

When a person runs into the side of the helicopter, It shouldnt explode

### Steps to Reproduce the Issue

1. Have a helicopter be spooled on the ground (With crew inside?)
2. Have an infantryman run into the side of the bird
3. Bird has a chance of launching itself and exploding

### **Screenshots**

N/A

### **Video**

So far this has been the only time its caught it on camera
https://www.twitch.tv/lildude0101/clip/GorgeousSecretiveHamburgerHumbleLife-ZqXmrj9cIGSUF07H

### **Additional context**

So far I havent been able to reproduce this consistantly, Ill update this issue with footage and anything I discover

**Comment by SekiAlpha** [comment]
This can happen with almost all helicopter in AFM including vanilla helicopters. The fix for this bug will probably have to be done by bohemia.
