### ISSUE TITLE
Bug: Helo squating when player or ai pilot is in the pilot seat

### ISSUE THREAD

**Issue by sevn10** [Project-Hatchet/public_h-60#124]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [X] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

- https://pastebin.com/t4RWm4pZ

# Bug Report

### **Expected Behavior**

The H-60's should not squat when a pilot is in the helo

### Steps to Reproduce the Issue

1. Place any version of the H-60
2. Have a player or ai sit in the pilot seat

### **Screenshots**

![20210324130327_1](https://user-images.githubusercontent.com/71986910/112361944-4717c080-8caa-11eb-9028-7e802dbd7968.jpg)

![20210324130338_1](https://user-images.githubusercontent.com/71986910/112361985-526aec00-8caa-11eb-8486-1b892867e289.jpg)

**Comment by BroBeansCPG** [comment]
Thanks,

This is fixed for SFM and only appears now if the pilot has AFM on

**Comment by sevn10** [comment]
That would explain it, I only ever use AFM and didn't think to try SFM as well. Will this be fixed in AFM?
