### ISSUE TITLE
Bug: “LIGHTS” text will not go away on HMD when lights turned off

### ISSUE THREAD

**Issue by Oyu07** [Project-Hatchet/public_h-60#125]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

# Bug Report

## **Description:**

LIGHTS text on HMD will not go away when you turn lights off.

### **Expected Behavior**

LIGHTS text to go away

### Steps to Reproduce the Issue

1. Enable HMD
2. Turn on lights
3. Turn off lights
4. Notice lights text is still there

### **Screenshots**

Will add later
 (Unable to use laptop, cant add pic rn)

**Comment by allegedflora** [comment]
Can you please remake the link? Looks like github messed up here

**Comment by Oyu07** [comment]
> Can you please remake the link? Looks like github messed up here

Oh sorry, forgot to delete the default youtube link on the preset, and as for the screenshot, literally unable to navigate my laptop (both touchpad and mouse broke).
