### ISSUE TITLE
Bug: Co-Pilot camera resetting on enter/exit with laser active

### ISSUE THREAD

**Issue by 00Sherkan00** [Project-Hatchet/public_h-60#126]
# Prerequisites

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord

# Bug Report

## **Description:**
in co-pilot position, when we enter the camera, the laser pointer returns to the center in "GEOLOCK" mode. As soon as we leave the camera it returns to the center position even if we have locked a position.

### **Expected Behavior**
When you lock a point in the camera view at the co-pilot position, it should stay at the same place when you exit the camera mode, having the same thing as the pilot.

### Steps to Reproduce the Issue

Helicopter turning and flying if possible:
1. Getting into the co-pilot's seat
2. Enter the Camera mode
3. Choose a point 
4. Exit the Camera mode

### **Screenshots**
Inside camera :
![107410_20210328121401_1](https://user-images.githubusercontent.com/79503171/112757659-0a6e0100-8feb-11eb-9f83-6cafdd05c497.png)
outside camera :+1: 
![107410_20210328121409_1](https://user-images.githubusercontent.com/79503171/112757685-22de1b80-8feb-11eb-9f92-9012880712c4.png)

**Comment by allegedflora** [comment]
Are you running trackir by chance?

**Comment by 00Sherkan00** [comment]
With or without Track IR,  is the same issue.

**Comment by 00Sherkan00** [comment]
and it is always present in the rc2

**Comment by BroBeansCPG** [comment]
Issue is the laser mark is not following the co-pilots view, 

so upon exiting the camera snaps back to the laser's location as intended. 

Problem is, the laser isn't where the camera last was as it should be

**Comment by BroBeansCPG** [comment]
I believe this is related to - 
https://github.com/Project-Hatchet/public_h-60/blob/9fd7416d1b8d54a6ad8bfc9caf0f5f73407fbeeb/addons/uh60_flir/functions/fnc_perFrame.sqf#L30-L32
