### ISSUE TITLE
Bug: Pilot model not visible from gunner pos

### ISSUE THREAD

**Issue by BroBeansCPG** [Project-Hatchet/public_h-60#135]
## **Description:**
Pilot model (AI or Player) not visible from gunner seats in First Person (GAU-21 and Port Minigun tested)

### **Screenshots**
![img](https://i.gyazo.com/003fe78766818082015ce8c83a936b39.jpg)

**Comment by ampersand38** [comment]
FIxed in 0.4.0.1 htofix
