### ISSUE TITLE
Bug: Numbers flicker when using the startup help/option on the MFD

### ISSUE THREAD

**Issue by Oyu07** [Project-Hatchet/public_h-60#142]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ *] I checked the documentation and found no answer
- [ *] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [ *] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

# Bug Report

## **Description:**

Numbers flicker when using the startup help/option on the MFD

### **Expected Behavior**

There to be no flicker and lights being on constant
### Steps to Reproduce the Issue

1. use the bottom MFD and open startup engine
2. Look at the numbers

### **Video**

Got a youtube link
- [Youtube link](https://youtu.be/ODkt_qlXkYw)

### **Additional context**

It was SUPER foggy on the server, and yes it was on server, couldn't see more than 50 meters that could be why?

**Comment by BroBeansCPG** [comment]
Any extra mods?

**Comment by Oyu07** [comment]
> Any extra mods?

 Yes, but I have used these mods for a year now and this didn't happen before. 
 Here is the mod HTML/Preset if you want to see it
 
 https://drive.google.com/file/d/1KiQqiRwpVLZWOqglQqwkN3x2OGuBREym/view?usp=sharing
 
 Download and it should open the classic arma preset/mod screen on browser

**Comment by BroBeansCPG** [comment]
Can you try reproduce it please? Without the extra mods?

**Comment by A26mike** [comment]
Not reproduceable
