### ISSUE TITLE
Bug: FLIR in MFD does not work

### ISSUE THREAD

**Issue by Oyu07** [Project-Hatchet/public_h-60#143]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [  ] I checked the documentation and found no answer
- [  ] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [  ] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

# Bug Report

## **Description:**

As the title says, when opening FLIR on MFD in the cockpit, it is just blank. (99% sure you guys already know this but blame donov for pushing me to do a bug report)

### Steps to Reproduce the Issue

1. Use the camera and see it is normal
2. go back to the cockpit and select FLIR. (Saw this in co-pilot far left screen)
3. Realise that it is empty/black/blank

### **Video**

- [Youtube link](https:/youtube.com)

### **Additional context**

Noticed during the operation, wanted to see the camera while being in the cockpit because the camera turns slower for co-pilot and wanted to look around with my eyes, and realized that it ain't working.

Note: still don't understand how to check the boxes

**Comment by BroBeansCPG** [comment]
[x] <— is how you do it 

Thanks this has been known for a while

**Comment by A26mike** [comment]
FLIR MFD was disabled for FLIR BLOCK 2 issue
Yax had some features planned for it and called it Block 2, should be on the "issues" or "projects" page
