### ISSUE TITLE
Bug: Helicopter inputs active while in map

### ISSUE THREAD

**Issue by zeidlos** [Project-Hatchet/public_h-60#145]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  
# Bug Report

## **Description:**
Helicopter takes inputs while in the map. 

### **Expected Behavior**
Helicopter should ignore keyboard and mouse input while player is working in the map.

### Steps to Reproduce the Issue
1. Spool up the chopper
2. Go into the map
3. Press shift for placing a waypoint/map waypoint
4. Move the mouse
5. Explode

**Comment by BroBeansCPG** [comment]
Are you 100% sure this doesn't happen in vanilla helicopters? 

I know for a fact keyboard inputs are still recognised, I'm not sure about mouse axis. 

@Project-Hatchet/qa-team
