### ISSUE TITLE
Bug: Ace fast-roping results in grave injuries to everyone using it

### ISSUE THREAD

**Issue by Kill3rCat** [Project-Hatchet/public_h-60#149]
# Bug Report

## **Description:**

When fast-roping from the UH-60M Blackhawk, passengers have the option to fast-rope either by pressing F on the fast rope Hatchet action, or to fast-rope by using ACE Interaction.

When using Hatchet Fast roping, everyone who used the F action died, but when we tested with everyone using the ACE interaction, everyone reached the ground safely.

### **Expected Behavior**

Fast rope without casualties

### Steps to Reproduce the Issue

1. All aboard
2. Take-off, stable hover
3. Deploy FRIES system
4. Deploy ropes
5. Wait until rope is on the deck
6. Fast rope using Hatchet
7. Spin and die horribly

### **Additional context**

When tested only using ACE interaction on the Hatchet UH-60M instead of the Hatchet interactions, the fast roping went smoothly with no casualties sustained.

**Comment by A26mike** [comment]
Temp fix  Add check if rope is on the ground or time delay

**Comment by BrettMayson** [comment]
At a quick glance the code looks correct, I'll need to actually test this in game. Don't have any mods setup for this though. Will need a few days to get more info.

Any video anyone can provide would be a great help too.

**Comment by BroBeansCPG** [comment]
Not just isolated to hatchet interaction

**Comment by nikmu3000** [comment]
the bug ist still there ;(
