### ISSUE TITLE
Bug: Most actions won't work for remote controlled units

### ISSUE THREAD

**Issue by BrettMayson** [Project-Hatchet/public_h-60#154]
# Bug Report

## **Description:**
Most hatchet interactions won't work for remotely controlled units.

### **Expected Behavior**
Every interaction should work as expected for remote controlled units

### Steps to Reproduce the Issue

1. Place a vehicle
2. Place a unit
3. Remote control the unit
4. Attempt to fast rope via hatchet interactions

**Comment by BroBeansCPG** [comment]
Is this more of a framework issue?

**Comment by BrettMayson** [comment]
It is not
