### ISSUE TITLE
FR: Add/remove skis via ace interact

### ISSUE THREAD

**Issue by BroBeansCPG** [Project-Hatchet/public_h-60#155]
Add ace option to add/remove skis for gameplay enhancement

**Comment by ampersand38** [comment]
I think ACE actions should be for stuff that needs to be reconfigured mid-mission. Skis can be added by mission-maker or zeus in garage, which seems to be good enough?

**Comment by AdozenBABYdogs** [comment]
> I think ACE actions should be for stuff that needs to be reconfigured mid-mission. Skis can be added by mission-maker or zeus in garage, which seems to be good enough?

The line of logic with doing Ace interactions was that it can be done mid mission, as required (Just like the actual platform can).  I think the solution should be to add a check box for mission makes to add skis, similar to how ACE fastroping works

**Comment by BroBeansCPG** [comment]
Service menu when

**Comment by AdozenBABYdogs** [comment]
When you make it :p

**Comment by ampersand38** [comment]
> check box for mission makes to add skis

This is available in Garage

**Comment by BroBeansCPG** [comment]
Happy to close this now it's in garage
