### ISSUE TITLE
Model: Blue line showing in cabin for pilot or co-pilot of MH-60 and MH-60 DAP

### ISSUE THREAD

**Issue by sevn10** [Project-Hatchet/public_h-60#157]
# Model Error report 

## **Description:**

- When in either the pilot or co-pilot seat of an MH-60 or MH-60 DAP when looking back into the cabin a blue line can be seen running through roughly the middle of the cabin. This does not occur on other versions or from other seats. 

### **Screenshots**

![20210912133014_1](https://user-images.githubusercontent.com/71986910/132997612-6e70f259-f8d6-4429-89a6-b78568131722.jpg)

**Comment by ampersand38** [comment]
It's due to the cockpit doors selection not including the hinges in viewPilot lod https://youtu.be/adrlST1wS_w
Fixed 
![image](https://user-images.githubusercontent.com/11483210/146072329-ddf6daac-7cd0-41fa-afdc-12bdcc7d430f.png)

**Comment by sevn10** [comment]
Interesting, so that should be a semi easy fix to correct the lod?

**Comment by ampersand38** [comment]
FIxed in 0.4.0.1 htofix
