### ISSUE TITLE
Feature request: RHS & CUPS weapon positioning fix

### ISSUE THREAD

**Issue by sevn10** [Project-Hatchet/public_h-60#159]
## **Is your feature request related to a problem? Please describe.**

Currently when using RHS or some of the CUPS weapons on pylons the positioning is too far back for the DAP or Knighthawk with pylons. 

For RHS it happens with the following:
- DAGR (M310)
- DAGR (M299)
- AGM-114L (M310)
- AGM-114L (M299)
- AGM-114K (M310)
- AGM-114K (M299)
- AGM-114M (M310)
- AGM-114M (M299)
- AGM-114N (M310)
- AGM-114N (M299)
- M151 Hydra (M260)
- M151 Hydra (M261)
- M229 Hydra (M260)
- M229 Hydra (M261)
- M257 Hydra (M260)
- GAU-19/A

For CUPS it happens with the following:
- 2x AGM-114K
- 2x AGM-114L
- M230 Chaingun Pod

## **Example Screenshot**

![20210912130842_1](https://user-images.githubusercontent.com/71986910/132998084-4b8b8d9a-f1fd-4156-9b60-26313354f095.jpg)

## **Describe the solution you'd like**

Not sure if it's possible without changing the model and it may be out of the scope of the mod, but ideally those weapons systems could be shifted to line up with the pylons. 

## **Describe alternatives you've considered**

If it's not possible to correct the positioning I think it would be good if we could hide those selections on the pylon system to present a cleaner list and only options that do look and work correctly with the mod.

**Comment by ampersand38** [comment]
The pylons are already animated to move forward and back between the LASS and ESSS positions. By increasing the range of the animation and detecting what mod the loaded pylonMagazine is from, we can set the correct position for it.

**Comment by ampersand38** [comment]
https://youtu.be/LC099-Mpbjc

**Comment by sevn10** [comment]
This is so awesome and works great from my tests so far.

**Comment by ampersand38** [comment]
FIxed in 0.4.0.1 htofix
