### ISSUE TITLE
Feature request: Seperate UVs for doors

### ISSUE THREAD

**Issue by sevn10** [Project-Hatchet/public_h-60#160]
## **Is your feature request related to a problem? Please describe.**

If we are going to make a change to the model and UVs would it be possible to have separate UVs for the left and right front and cabin doors? It would be cool for having additional numbering or more accurate labeling when doing skin design. 

## **Describe alternatives you've considered**

If that's not possible would it somehow be possible to add overlay areas where just the number textures could be swapped out. Similar to how the USAF mod allows for custom numbering or in DCS how the board number can be changed.

**Comment by PervonHarke** [comment]
This would make a lot of skins possible.
