### ISSUE TITLE
Ordnance Improvements

### ISSUE THREAD

**Issue by TheProdddd** [Project-Hatchet/public_h-60#161]
## **Is your feature request related to a problem? Please describe.**

-30MM feels like it doesn’t pack a punch against infantry 

## **Describe the solution you'd like**

- Add different belt types for the DAP!

## **Describe alternatives you've considered**

- If not feasible to add ammo types, consider increasing the splash damage against infantry and light armored vehicles 

## **Additional context**

- Played a op with my unit yesterday, was hitting a emplaced gun with a gunner on it, and used 20-30 rounds on the dap within very close proximity to the gunner , but he wasn’t dying. I also then spawned a squad in eden editor, and the 7.62 was a bit more effective then the 30MM, but in some situations, it would be better to sue the 30MM

**Comment by BroBeansCPG** [comment]
Potential list of new ammotypes 

- [ ] 30mm HEDP
- [ ] 30mm AP
- [ ] Hydra M151 HEDP
- [ ] Hydra M247 HEAT
- [ ] Hydra M255E1/A1 Flechette
- [ ] M257 Illum
