### ISSUE TITLE
Feature request: Hiding UI features

### ISSUE THREAD

**Issue by sevn10** [Project-Hatchet/public_h-60#162]
## **Describe the solution you'd like**

It would be great if we had a way to selectively turn off some or all UI elements to create a cleaner experience for users familiar with using the H-60. It would also make for better videos and screenshots from the bird. Ideally the UI could be decluttered to the point where only cursor and interaction selector show. 

In my screenshot I've pointed out all the elements that would be nice to be able to have an option to hide individually or as a group. I'm not sure if the default scroll wheel menu can be hidden without rebinding it to other controls, but it would be nice if there were a way to prevent it from popping up when interacting on items in the helo.  

## **Screenshot**

![20210912145754_1b](https://user-images.githubusercontent.com/71986910/132999936-04a31de2-4439-4127-89e6-6562fde0c0ee.jpg)

**Comment by BroBeansCPG** [comment]
Top left - you can't hide, we've hid as much as we could (I believe) 

Middle - is meant to have settings to hide/selectively show some parts of it, it's just broken

Bottom Left is debug messages sent into the chat, these will be disabled one day. This one you can move off your screen with the layout editor though

**Comment by FatLurch** [comment]
The systemChat can now be hidden via the Addon settings screen. I think @ampersand38 was able to hide the bit at the top left (green box) as well.

I have a solution in mind for hiding the vanilla scroll items.

**Comment by sevn10** [comment]
Yep, can confirm the hide works from the addons now.
