### ISSUE TITLE
Feature request: Ability to hide the hoist

### ISSUE THREAD

**Issue by Riverman02** [Project-Hatchet/public_h-60#164]
## **Is your feature request related to a problem? Please describe.**
No

## **Describe the solution you'd like**
Ability to hide the hoist on regular transport aircraft in order to bring more importance to the dedicated rescue models (HH, UH Medevac)

## **Describe alternatives you've considered**
Only alternative I would see is to restrict the hoist to only the rescue models but unsure how much more trouble that would be since they all use the same base model (as far as I understand)

## **Additional context**
As far as I know IRL, Air Assault units don't have the hoist installed on aircraft as it isn't required for their mission

**Comment by ampersand38** [comment]
Added in 0.4.0.1 htofix
