### ISSUE TITLE
Bug: M230 30mm muzzle flash coming out of Minigun barrel on MH-60M DAP

### ISSUE THREAD

**Issue by WanderingViking** [Project-Hatchet/public_h-60#165]
# Bug Report

## **Description:**

Noticed when ground testing the MH-60M DAP weapons, that the 30MM's flash comes out of the Minigun barrels. This was noticed when it was mounted on the right side pylon. Not tested on left side. 

### **Expected Behavior**

Muzzle flash to come out of the 30mm barrel.

### Steps to Reproduce the Issue

1. Spawn MH-60M DAP with M230 30MM 
2. Fire 30MM 
3. Observer flash

**Comment by ampersand38** [comment]
This appears to be no longer the case now.
