### ISSUE TITLE
Feature request: DAGR pod

### ISSUE THREAD

**Issue by KaelabOspeec** [Project-Hatchet/public_h-60#170]
## **Is your feature request related to a problem? Please describe.**

-Requesting the addition of the DAGR and/or APKWS weapon systems to the MH-60M DAP platform.
- change text here 

## **Describe the solution you'd like**

- change text here 
- change text here 

## **Describe alternatives you've considered**

- change text here 
- change text here 

## **Additional context**

- change text here 
- change text here

**Comment by BroBeansCPG** [comment]
#128
