### ISSUE TITLE
Model:  errors when the vtx_UH60M_SLICK is placed 

### ISSUE THREAD

**Issue by A26mike** [Project-Hatchet/public_h-60#177]
17:31:04 vtx_UH60M_SLICK: hh60flares - unknown animation source hh60flares_show
17:31:04 vtx_UH60M_SLICK: positionlights_show - unknown animation source positionlight_show
17:31:04 vtx_UH60M_SLICK: flir_direction - unknown animation source pilotCameraRotX (defined in AnimationSources::FLIR_DIRECTION)
17:31:04 vtx_UH60M_SLICK: flir_elevation - unknown animation source pilotCameraRotY (defined in AnimationSources::FLIR_ELEVATION)
17:31:04 vtx_UH60M_SLICK: gau21l_dir - unknown animation source gau21l_dir
17:31:04 vtx_UH60M_SLICK: gau21l_gunner - unknown animation source gau21l_dir
17:31:04 vtx_UH60M_SLICK: gau21l_gunner_legs - unknown animation source gau21l_dir
17:31:04 vtx_UH60M_SLICK: gau21l_elev - unknown animation source gau21l_elev
17:31:04 vtx_UH60M_SLICK: gau21r_dir - unknown animation source gau21r_dir
17:31:04 vtx_UH60M_SLICK: gau21r_gunner - unknown animation source gau21r_dir
17:31:04 vtx_UH60M_SLICK: gau21r_gunner_legs - unknown animation source gau21r_dir
17:31:04 vtx_UH60M_SLICK: gau21r_elev - unknown animation source gau21r_elev
17:31:04 vtx_UH60M_SLICK: minigunl_dir - unknown animation source minigunl_dir
17:31:04 vtx_UH60M_SLICK: minigunl_elev - unknown animation source minigunl_elev
17:31:04 vtx_UH60M_SLICK: minigunl__flash - unknown animation source axis_minigunl_barrels
17:31:04 vtx_UH60M_SLICK: minigunl_gunner - unknown animation source minigunl_dir
17:31:04 vtx_UH60M_SLICK: minigunl_gunner_legs - unknown animation source minigunl_dir
17:31:04 vtx_UH60M_SLICK: minigunr_dir - unknown animation source minigunr_dir
17:31:04 vtx_UH60M_SLICK: minigunr_elev - unknown animation source minigunr_elev
17:31:04 vtx_UH60M_SLICK: minigunr__flash - unknown animation source axis_minigunr_barrels
17:31:04 vtx_UH60M_SLICK: minigunr_gunner - unknown animation source minigunr_dir
17:31:04 vtx_UH60M_SLICK: minigunr_gunner_legs - unknown animation source minigunr_dir
17:31:04 There has to be at least one Exits defined in vtx_UH60M_SLICK
17:31:04 CargoBayDimensions has to be defined and not at same place in vtx_UH60M_SLICK. Current distance is 0.

**Comment by ampersand38** [comment]
If the animations don't apply the vehicle (ie the guns are not on the slick), it appears that it's harmless to have. https://dev.cup-arma3.org/T4065
