### ISSUE TITLE
Bug: ace fast rope bug

### ISSUE THREAD

**Issue by M829A3** [Project-Hatchet/public_h-60#178]
### Description:
After I deployed ropes, I found that the rope was shaking violently and spinning at high speed. Whether using ace interaction or pressing the F key for fast roping, the player will be out of roping in mid-air and fall to the ground.

### Expected Behavior:
Fast rope without casualties

### Steps to Reproduce the Issue:
1. Take-off, stable hover
2. Deploy FRIES system
3. Deploy ropes
4. Wait until rope is on the deck
5. Fast roping

**Comment by BroBeansCPG** [comment]
Duplicate of #149
