### ISSUE TITLE
Bug: Passengers Dismount Unevenly 

### ISSUE THREAD

**Issue by Riverman02** [Project-Hatchet/public_h-60#179]
# Bug Report

## **Description:**
When passengers dismount from their seat, 10 of them all spawn on the right side of the helicopter, causing collisions with the model and sometimes destroying the helicopter, especially when combined with uneven terrain. 

### **Expected Behavior**
Passengers should be evenly distributed with respect to the side they are on. The only passenger that spawns on the left side is seat number 1. 

### Steps to Reproduce the Issue
<!-- Provide an unambiguous set of steps to reproduce this bug.
1. Spawn H-60 
2. Load into the passenger seats
3. Get out of each one
4. 10 times out of 11, you will spawn on the right side

**Comment by PervonHarke** [comment]
I think collisions can also happen when only one passenger exits. Happened to me at least once with another player. 
(He went in and imminently double v'ed out causing the heli to be thrown 20 meters into the air and explode.)

**Comment by ampersand38** [comment]
Looking better now =) https://www.youtube.com/watch?v=Ic0paKXcGXs
