### ISSUE TITLE
Feature request: Change colour of HUD

### ISSUE THREAD

**Issue by Chillinthesnow** [Project-Hatchet/public_h-60#180]
As someone who is colour blind the green of the hud is unreadable for me. 

Would love to be able to change to the other primary colours (red, blue, yellow, white) so hopefully all us that are colourblind have an option that might work.

**Comment by AdozenBABYdogs** [comment]
Maybe add a menu customization section for the HUD and allow a custom RGB to be used, not sure how Arma would handle that but i think I've seen other mods with customizable huds.  Or we could add a colorblind check box that could switch the hud color to something more colorblind ish (not entirely sure what that would look like, but think of battlefield's colorblind option)
