### ISSUE TITLE
Request: Hiddenselection for ESSS retexture

### ISSUE THREAD

**Issue by McKronenberg** [Project-Hatchet/public_h-60#181]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# Texture error report 

## **Description:**
There is no texture file for the Knighthawks pylons. At least i cloud not find it. I  was told to open a bug Report 

###  **Screenshots**
![image](https://user-images.githubusercontent.com/84646172/134791193-22fc1ea5-b84e-457c-a42b-472393890a01.png)

**Comment by BroBeansCPG** [comment]
I wouldn’t say it’s a bug per se, it’s more of a request to support retextures
