### ISSUE TITLE
Feature request: TFAR Crew Radios

### ISSUE THREAD

**Issue by Riverman02** [Project-Hatchet/public_h-60#183]
The crew chief seats in the back do not have access to aircraft radios when TFAR is used. IRL there are ICS panels in the back that have the ability to monitor and transmit on the aircraft radios. This will make crew coordination easier and keep crew members from needing to pack radio backpacks.

**Comment by AdozenBABYdogs** [comment]
Just ICS, or does it also allow transmit over the same radio frequencies or should it just be two additional lr radios?

**Comment by Riverman02** [comment]
ICS is fine because TFAR adds intercom for the whole aircraft. It should just be two additional LR radios.s. If you want it to be realistic then all radios should be synced to the same frequencies but also you would need to be able to monitor 4 nets which TFAR doesn't support on one radio

**Comment by sevn10** [comment]
I'd like to expand this and request it for ACRE as well. It seems like only variants of the H-60 with seats in the back add access to the intercom. Either gun seat or in the case of the DAP, the hoist operator, should at least have access to the intercom.
