### ISSUE TITLE
HMD unreadable against daytime terrain AND request for default floating instruments option

### ISSUE THREAD

**Issue by Alienpickle** [Project-Hatchet/public_h-60#192]
## **Describe feature request.**

HMD is largely unreadable against daytime terrain background coloration.  Default aircraft HMD are notably thicker lines and brighter green than the H-60's.  The current HMD just disappears into the grass and trees with the coloration and thickness currently employed.  

Make green intensity 0,1,0 values and 2x thickness of what look to be 1px lines.  I note green color definition is currently 0.6 so perhaps just brightening it will fix things.  

Additional feature request:  Toggle option to display ARMA's floating instrument dials like stock aircraft, to give users with vision impairment an additional fallback method.

**Comment by Dicky-James** [comment]
Any chance for a red "daytime" option as well?  I know that's not exactly realistic, but for the sake of Arma it may be a good way to go.

**Comment by BroBeansCPG** [comment]
> Any chance for a red "daytime" option as well? I know that's not exactly realistic, but for the sake of Arma it may be a good way to go.

More likely would be an option where you can change it to whatever colour you want

**Comment by BroBeansCPG** [comment]
Closed for now #247
