### ISSUE TITLE
Bug: Simple Startup Mode Doesn't Appear to Burn Fuel

### ISSUE THREAD

**Issue by FatLurch** [Project-Hatchet/public_h-60#196]
# Bug Report

## **Description:**
When the H-60 is started in the simple startup mode, it appears to not burn fuel over time. 
This appears to be at a base level because running `fuel vehicle player` always returns 1.

### **Expected Behavior**
Aircraft burns fuel after being startup in simple mode

### Steps to Reproduce the Issue
1. Configure for simple startup in the addon options 
2. Scroll to "Engine On" and middle-click
3. Flip the generator and battery switches on so that the MFDs come up
4. Observe Fuel on MFD is constant at 2040 lbs (init value) 

### **Additional context**
The actual processing of fuel consumption appears to happen here in the code: https://github.com/Project-Hatchet/H-60/blob/b8e9d4d1fd85b0447424a73b9ff4413617caf496/addons/uh60_engine/functions/fnc_perSecond.sqf#L32

**Comment by BroBeansCPG** [comment]
This could be fixed by simple startup triggering scripted start up instead. 

Believe Yax may have mentioned this was meant to be a feature anyway so the MFD’s and other features still come online with simple startup

`sqf
// auto start
[vehicle player] spawn {
    params ["_heli"]; 
    sleep 1; 
    [_heli, ["startup", "b_gen1"], "ON"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_gen2"], "ON"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_batt1"], "ON"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_batt2"], "ON"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "fuelPump"], "APU BOOST"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "apucont"], "ON"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_apugen"], "ON"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_stbyinst"], "ARM"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_ignition"], "ON"] call vxf_interaction_fnc_scriptedInteract; 
    sleep 1; 
    [_heli, ["startup", "b_airsce"], "APU"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_fuelsys1"], "DIR"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_fuelsys2"], "DIR"] call vxf_interaction_fnc_scriptedInteract; 
    sleep 1; 
    [_heli, ["startup", "b_starter1"]] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "powerContRTD", "b_engpowercont1"], "FLY"] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "b_starter2"]] call vxf_interaction_fnc_scriptedInteract; 
    [_heli, ["startup", "powerContRTD", "b_engpowercont2"], "FLY"] call vxf_interaction_fnc_scriptedInteract; 
    sleep 1; 
    [_heli, ["startup", "apucont"], "OFF"] call vxf_interaction_fnc_scriptedInteract;
};`

**Comment by FatLurch** [comment]
Resolved by #259
