### ISSUE TITLE
Bug: sfm to maneuverable after cg update

### ISSUE THREAD

**Issue by FireStone1029** [Project-Hatchet/public_h-60#238]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x ] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  
after the sfm cg has moved the bird can do some crazy moves watch vid for reference 
https://youtu.be/Zck6KPiZHiw

**Comment by Dicky-James** [comment]
AFM appears to be quite maneuverable too.  Not sure if it's as excessive as SFM.  Providing an AFM video for reference.

https://youtu.be/Gfinjf4OhVo

**Comment by BroBeansCPG** [comment]
Will compare with a previous build. 

In the meantime you can check out the QA build in the Internship channel to see the sfm hotfix

**Comment by FireStone1029** [comment]
> AFM appears to be quite maneuverable too. Not sure if it's as excessive as SFM. Providing an AFM video for reference.
> 
> https://youtu.be/Gfinjf4OhVo

Are you using simple collective in the vid?

**Comment by Dicky-James** [comment]
> > AFM appears to be quite maneuverable too. Not sure if it's as excessive as SFM. Providing an AFM video for reference.
> > https://youtu.be/Gfinjf4OhVo
> 
> Are you using simple collective in the vid?

Nope.  All AFM.

**Comment by ampersand38** [comment]
FIxed in 0.4.0.1 htofix
