### ISSUE TITLE
Bug: hud waypoint information displaying the wrong bearing 

### ISSUE THREAD

**Issue by FireStone1029** [Project-Hatchet/public_h-60#239]
![image](https://user-images.githubusercontent.com/34311095/147376700-53e79f06-9c76-4df9-a4f6-4a574eedd28a.png)
says -30 instead of 330

**Comment by Dicky-James** [comment]
It looks like the waypoint TO information (course and time) is based off of the orientation of the helicopter now and not off of magnetic north.  It will show +### degrees for waypoints to the right and -### degrees for waypoints to the left.  These are heading deviations, not magnetic headings for a course.  If you spin around a bunch, sometimes the values go up to +/-359 degrees.

**Comment by Dicky-James** [comment]
A more complete depiction of what's going on.  Basic details in the video description.
https://youtu.be/uXCE22XzkC4

**Comment by ampersand38** [comment]
https://user-images.githubusercontent.com/11483210/147393657-6bac144e-f7e1-408c-aded-c3f819a72c76.png

**Comment by FatLurch** [comment]
_Appears_ to originate here:
https://github.com/Project-Hatchet/H-60/blob/bbf4686caae8911c50875edc50d9f416e713c0e4/addons/uh60_fms/functions/fnc_updateWaypointInfo.sqf#L29

The current calculation for waypoint heading used with userValue 0 (used as heading for waypoints) can return a negative heading.

Idea for fix: Add 360 then mod 360?

`(private _waypointDirection = (_center getDir _position) - _startDir + 360) mod 360;`

**Comment by Dicky-James** [comment]
The bearing was not erroneous prior to the update.  There must be a line in the old file that had the correct values and such.
