### ISSUE TITLE
Fix the firing direction for flares

### ISSUE THREAD

**Issue by YannikH** [Project-Hatchet/public_h-60#24]
Currently flares fire straight out from the tail, make sure they instead fire from the various flare launchers (don't forget the HH-60 gear flares)

**Comment by BroBeansCPG** [comment]
Need to add memory points on the model for the different flare launchers 

Then add to cfgVehicles (note HH60 will need it's own entry) 
`		memoryPointCM[]=
		{
			"flare_launcher1",
			"flare_launcher2"
		};
		memoryPointCMDir[]=
		{
			"flare_launcher1_dir",
			"flare_launcher2_dir"
		};`
