### ISSUE TITLE
AFM Ground Taxi Behavior

### ISSUE THREAD

**Issue by Dicky-James** [Project-Hatchet/public_h-60#240]
Request the behavior for ground taxiing be readjusted to settings similar to the previous values.  At the moment, ground taxiing in AFM is somewhat dangerous due to the requirement of full forward collective in conjunction with a higher power setting of >30% collective and Cont levers at flight mode.  Taxiing is unstable and the helicopter is extremely difficult to control.

**Comment by Dicky-James** [comment]
Further detailing of feature issues are in the video description.
https://youtu.be/Qpw-P1j9GuA

**Comment by Riverman02** [comment]
Upon testing of my own and review of the video, it is simply just not ground taxiing. It acts as if the wheels are already off the ground even though they may appear to be touching the ground. The high power setting ends up picking you up before the wheels are able to start rolling which I believe is the cause of the drift and yaw movements. 

While full forward _cyclic_ and Q > 30% is abnormal, PCLs at FLY is not.

**Comment by Dicky-James** [comment]
Is it possible to simply halve the value of the increase to wheel friction so that PCLs at FLY and throttle at Q~15% would induce a forward roll?  I would assume that to be enough to avoid most taxi capabilities with PCLs at IDLE (then again, I haven't a clue!)

**Comment by Riverman02** [comment]
Torque actually sits around 20% when at flat pitch and only really requires no more than 25% to get it rolling. At Idle, Q should be around 8-10%. We're experimenting with some flight model tweaks to better reflect IRL characteristics. Honestly couldn't say what this will mean for the future of ground taxiing so we'll just have to wait and see what magic we can conjure up.

**Comment by Dicky-James** [comment]
Error on my part.  I meant to reference C, not Q for the throttle settings.

As of now, C>=31% with full forward on collective will "taxi".  C~15% is what I meant for inducing forward roll.
