### ISSUE TITLE
Bug: Unable to load stretchers.

### ISSUE THREAD

**Issue by Dicky-James** [Project-Hatchet/public_h-60#241]
Unable to load stretchers into any of the helicopters regardless of seating arrangement.  The Slick used to be able to accept up to 5 stretchers and the MH-60M took up to 3 stretchers.  None of them (including the MedEvac which needs it most) can take any loads.  I included editor settings I tried out after this discovery just in case it was an error on my part.

![20211224200257_1](https://user-images.githubusercontent.com/84091576/147377339-f4cf6472-6967-4868-888c-f0d8de21b3c4.jpg)
![20211224202131_1](https://user-images.githubusercontent.com/84091576/147377342-b64e072d-c08a-4c30-9a00-f3b62a9a105c.jpg)
.

**Comment by ampersand38** [comment]
Thank you for trying that right away =)

**Comment by Dicky-James** [comment]
With regards to the MedEvac and stretchers in particular, is it possible to add in the “center, front” seat that exists in one of the other models? It’s the position facing rear between the two door-gun seats. It’s perfect positioning for a flight medic working on patients loaded in the stretchers and leaves the four back seats open for minor casualties or transport. 

-Richard
