### ISSUE TITLE
Request: Unarmed UH-60M

### ISSUE THREAD

**Issue by Dicky-James** [Project-Hatchet/public_h-60#242]
When removing the door guns on the UH-60M, the occupants of those seats are unable to look around regardless of whether or not they are turned out.  Getting out of the helicopter will also cause a black screen that requires exiting back into the editor.  My setting are 1st person locked, so I used my Personal Arsenal to get the exterior view.  These shots are all from the left door gun seat.

![20211224203018_1](https://user-images.githubusercontent.com/84091576/147377445-c7c946c7-18f8-4b6f-8766-c28d501075ba.jpg)
![20211224203029_1](https://user-images.githubusercontent.com/84091576/147377449-4bc01c0a-f3ac-407a-994c-d529325da448.jpg)
![20211224203040_1](https://user-images.githubusercontent.com/84091576/147377451-7550d4a6-0888-4f31-aa5b-f0b11d57ae86.jpg)
![20211224203044_1](https://user-images.githubusercontent.com/84091576/147377455-b17816d9-90f8-4f38-b46c-b066b51e69f9.jpg)

**Comment by ampersand38** [comment]
So turrets aren't really something that can be switched by hiding parts. For now, if you want to use the FFV seats, use the MEDEVAC. We'll keep the issue as a request for a specific seating arrangement though.

**Comment by Dicky-James** [comment]
Ah, gotcha. That makes more sense now. Thank you!

-Richard

**Comment by BroBeansCPG** [comment]
@ampersand38 are we able to lock the turret seat if the gun is hidden? Or does the seat animation look fine it’s just the turning out which bugs?

**Comment by ampersand38** [comment]
We could investigate having both the turret and the ffv configured, and have one locked based on the animation. I'm not sure how it'll affect stuff like the crew info side panel and seat count or what else.

**Comment by Dicky-James** [comment]
Since this isn't really an issue and is dependent on airframe, I'm going to close this.
