### ISSUE TITLE
Bug: Waypoint direction incorrect

### ISSUE THREAD

**Issue by ampersand38** [Project-Hatchet/public_h-60#246]
![image](https://user-images.githubusercontent.com/11483210/147393657-6bac144e-f7e1-408c-aded-c3f819a72c76.png)
Value goes negative.
0 deg is centered on heli-to-waypoint instead of North

**Comment by Dicky-James** [comment]
I provided a video for reference in an earlier write-up about this issue.  The time-to-waypoint might need to be looked at as well as it appeared to act differently in its calculations.

**Comment by ampersand38** [comment]
Duplicate of #239
