### ISSUE TITLE
Bug: FLIR MFD point track behaves differently to fullscreen pilotcamera?

### ISSUE THREAD

**Issue by kiel2000** [Project-Hatchet/public_h-60#248]
The fullscreened' FLIR has an easy time locking onto vics, the FMD  ((MFD?)In cockpit) FLIR seems to have a hard time locking onto them (i was not able to succsefully lock onto any) and often looses track of them (even if the camera can turn in that direction and no part of the airframe is covering the target)

**Comment by ampersand38** [comment]
I do see that it sometimes freezes when tracking, but then it picks up again after 5-10 seconds. Can you confirm?

**Comment by kiel2000** [comment]
Ill get back to you tomorrow when ill test it again (GMT so it’s late)

**Comment by YannikH** [comment]
Should be largely improved in 0.6
