### ISSUE TITLE
Feature: MedEvac Variant w/ Red Cross

### ISSUE THREAD

**Issue by Dicky-James** [Project-Hatchet/public_h-60#256]
Looking for a standard American red cross in place of the red diamond for the MedEvac variant.

**Comment by sevn10** [comment]
It's not going to happen officially. There is some sort of restriction the red cross has on that, which is why base game Arma and this mod doesn't use it. Yax told me about it when I was submitting the textures and the conversation should be searchable in the discord.

**Comment by Dicky-James** [comment]
Shoot...  I know RHS has their MedEvac modelled with a red cross, which is why I ask.

**Comment by sevn10** [comment]
If it were approved I'd submit my alternate textures, but I don't believe it will be.
