### ISSUE TITLE
New door gunner weapons? 

### ISSUE THREAD

**Issue by lutherwolf** [Project-Hatchet/public_h-60#257]
is it at all possible to add a variety of new weapons for door gunner slots. for example an M2 or the m240. these would be mounted guns of course but would replace the minigun and allow for more loadout set-ups when it comes to logistical aircraft. if it is at all possible it would be amazing to see with the detailed aircraft.

**Comment by FireStone1029** [comment]
Other variants with different weapons on them are being work on there is just other issues that we are prioritizing first

**Comment by BroBeansCPG** [comment]
M2/Gau is pretty well done, it just needs integration which could still be a while away

M240 will probably never happen :)

**Comment by Riverman02** [comment]
One idea I had the other day was as an alternative to the 240 if we could mount the vanilla SPMG since that's the closest looking to a 240. Though upon some more research, I found that it's a DLC item.

**Comment by BroBeansCPG** [comment]
The irony is it’d probably be easier to make a 240 from scratch rather than trying to use the spmg model. Without the MLOD we couldn’t add it to our model. 


i’d love to see a 240 model, but it’ll likely not happen, plus the things useless anyway 😆

**Comment by Riverman02** [comment]
I just hate miniguns in video games honestly lol
