### ISSUE TITLE
Feature Request: Ability to adjust UI clutter

### ISSUE THREAD

**Issue by Riverman02** [Project-Hatchet/public_h-60#263]
Create an add-on option for different levels of interaction with the cockpit. Available options I think would be attractive:

Full: The way it is now. Highlights button/switch with instructions of how to manipulate it

Decluttered: Removes instructions but still highlights the selected button/switch

Minimal/Off: Removes all context outside of the X cursor. Maybe the cursor could change color when over a selectable button/switch

**Comment by BroBeansCPG** [comment]
This actually already exists in the latest version of the framework, still need to iron out a major bug before it can be pushed to steam :)

**Comment by Riverman02** [comment]
Oh neat!

**Comment by BroBeansCPG** [comment]
duplicate of #162
