### ISSUE TITLE
Feature request: Center-Front Seat Availability

### ISSUE THREAD

**Issue by Dicky-James** [Project-Hatchet/public_h-60#266]
Did a search since I thought I mentioned this, but couldn't find it...

Can the center-front seating position be added to at least the MedEvac model?  It's a good position for a flight medic to tend to patients on stretchers and not occupy any of the rear bulkhead passenger seats.

**Comment by ampersand38** [comment]
With stretchers loaded in, you already still have 2 ffv seats available 
![image](https://user-images.githubusercontent.com/11483210/148659847-39e35e3b-a6a3-4fca-b944-c042032282a2.png)

**Comment by Dicky-James** [comment]
Didn't realize it was already addressed.  Awesome!
