### ISSUE TITLE
Feature request: Add hoist operator turnout option

### ISSUE THREAD

**Issue by AdamAb44** [Project-Hatchet/public_h-60#268]
Add turnout option, similar to door gunner turnout, for the operator of hoist. Currently, when the hoist is lowered to the ground, the operator in the helicopter can't see it through the heli's floor.

**Comment by ampersand38** [comment]
![image](https://user-images.githubusercontent.com/11483210/148662204-dc193187-9374-4ecf-82fb-02030266b524.png)
![image](https://user-images.githubusercontent.com/11483210/148662208-56d99cbf-9b1b-426d-b7d3-cc519ee87837.png)

**Comment by AdamAb44** [comment]
Nice, but the gun has to be unholstered and in high-ready, no?

**Comment by FatLurch** [comment]
It looks like this could be setup so the hoist operator *never* has their weapon out, which is a tradeoff.

hideWeaponsGunner = true

Boolean If true, the gunners weapons (his rifle) will not be displayed.

**Comment by ampersand38** [comment]
We'll just have to make an invisible pistol or something =p
https://d1ldvf68ux039x.cloudfront.net/thumbs/photos/2011/6414547/1000w_q95.jpg

**Comment by AdamAb44** [comment]
How about making (defining) the Hoist operator position as a gunner, instead of a passanger? Then the gunner turnout option would be applicable, no? (I guess with some animation tweaks)
Then it should be possible to
1) use the gun
2) turnout without having to go high-ready
