### ISSUE TITLE
Remove duplicate main.pbo from steam build

### ISSUE THREAD

**Issue by YannikH** [Project-Hatchet/public_h-60#28]

**Comment by allegedflora** [comment]
Causing signature issues
![image](https://user-images.githubusercontent.com/37432237/107737618-b211c700-6cfc-11eb-92a3-0fd7572d76a8.png)
![image](https://user-images.githubusercontent.com/37432237/107737664-dbcaee00-6cfc-11eb-87ac-fcce5301f783.png)
![image](https://user-images.githubusercontent.com/37432237/107737923-85aa7a80-6cfd-11eb-9165-c4a82747088b.png)

**Comment by ampersand38** [comment]
fixed in 0.2.1
