### ISSUE TITLE
Bug: FRIES causing random spinning

### ISSUE THREAD

**Issue by chrisrhayward** [Project-Hatchet/public_h-60#282]
Mod Version: Development (Latest)
Reproducible: Extensively

Issue:
When using the FRIES on any H-60 helicopter, regardless of using the Hatchet keybinds or the ACE interaction options, players on the rope spin rapidly for approximately 5 seconds (seems to be about the same amount of time a successful descent animation takes), before falling down to the ground from the original height, now detached from the rope. This happens regardless of time spent waiting for the rope to settle on the ground, and the rope attachment is always visibly spinning.

Possible Causes:
Rope object spinning rapidly, potentially by the rotor downdraft

**Comment by BroBeansCPG** [comment]
Duplicate #149
