### ISSUE TITLE
Bug: **EDITED 2x** MFD FLIR not synchronizing between pilot and co-pilot 

### ISSUE THREAD

**Issue by Buster6483** [Project-Hatchet/public_h-60#299]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  
# Bug Report

### **Description:**
I've come across the problem of when me and another person get into the same MH-60 (with pylons) and the person in the pilot seat starts the engine and opens the FLIR on the MFD that when they move the camera around it's only visible to them but when the co-pilot moves their camera the pilot's camera snaps to the same position the co-pilot is moving it to.

What I mean is when the pilot moves their camera it doesn't move for the co-pilot but when the co-pilot moves their camera it works as intended where both MFDs sync up without issue.

Getting out and changing seats just reverses the problem, so if the co-pilot moves to the pilot seat they will still have control over the entire FLIR but when the previous pilot gets into the co-pilot seat and tries to move the camera it will only move on their screen

### **Expected Behavior**
The expected behavior would be that when the (co-)pilot moves their camera, it shows that movement for both the pilot as the co-pilot on the MFDs that are displaying the FLIR page

### Steps to Reproduce the Issue
1. Get into the pilot seat
2. Get another player into the co-pilot seat
3. Start the engine as you would normally
4. Move your FLIR camera
5. Document changes in co-pilot's view (camera will be on default position)
6. Have the co-pilot move their FLIR camera
7. Document changes in pilot's view (camera will snap to default position before following the co-pilot's camera movement)

# **EDIT**
The person that moves the camera first is the one that glitches it, the person that moves it after the initial move by person #1 will have full controll of the FLIR

# **EDIT 2**
It all works fine if you don't use slew but instead ctrl+ wasd

**If a video of this issue is needed please let me know, I'll try to get a second player to record their POV so you can see it from both angles**

**Comment by BroBeansCPG** [comment]
@Buster6483 a video would be good to help :)
