### ISSUE TITLE
Major flaw in build system 

### ISSUE THREAD

**Issue by A26mike** [Project-Hatchet/public_h-60#30]
-Problem was noticed on latested steam build [Hatchet H-60 pack](https://steamcommunity.com/sharedfiles/filedetails/?id=1745501605)
it appears that the bisign key's do not get wiped from the release folder per build 

![image](https://user-images.githubusercontent.com/36065925/107733939-3860e580-6cca-11eb-8115-794a851022e7.png)

## The actual release folder on github is fine 
![image](https://user-images.githubusercontent.com/36065925/107734805-4283e380-6ccc-11eb-83f3-4f166b7851c8.png)

**Comment by ampersand38** [comment]
Are you running `make.py force checkexternal release`?

**Comment by YannikH** [comment]
works fine on my machine
