### ISSUE TITLE
Bug: MFD Displays FLIR and TAC while off

### ISSUE THREAD

**Issue by AdozenBABYdogs** [Project-Hatchet/public_h-60#305]
## **Description:**
MFD #3 continues to display both FLIR and TAC images despite being off on current build of Main

### **Expected Behavior**
There should be no payload feed or image of the map

### Steps to Reproduce the Issue
Startup the H-60
Turn off BATT-2
Interact with the #3 MFD (select either FLIR or TAC)

**Comment by Kill3rCat** [comment]
Can repro, has been the case for a long time now
