### ISSUE TITLE
Bug: Rotor Blade Contact

### ISSUE THREAD

**Issue by Riverman02** [Project-Hatchet/public_h-60#309]
Rotor Blades contact objects inside the disc when a player occupies the aircraft causing the engines to fail and rotor blades to stop. 

No damage done to player

Contact point appears to be even with the tip caps along the tail boom section, just before reaching the tail pylon. About even with the localizer antenna.

References:
https://www.youtube.com/watch?v=LCLiwZDQMEU

https://youtu.be/zInvm1keBag

https://www.youtube.com/watch?v=PrEX3Ug_h_8

**Comment by MarkieMarky** [comment]
How is it going with this one?

**Comment by BroBeansCPG** [comment]
fixed in 0.5.1
