### ISSUE TITLE
Bug: DAP Pilot/Co-pilot Issues

### ISSUE THREAD

**Issue by sevn10** [Project-Hatchet/public_h-60#313]
# Bug Report

## **Description:**

Since the co-pilot in the DAP is currently unable to Ctrl Right Click to enter the full screen of the FLIR we attempted to have the pilot seat pass flight controls to the co-pilot and have the pilot work the FLIR and weapons. However, in this arrangement the pilot's seat FLIR view in full screen is unmovable and is only moveable via the MFD. In addition, indication of selected weapon is broken on the HMD for the co-pilot seat and the pilot seat cannot currently use the HMD due to the HMD turning off bug. In addition to these issues it was experienced that the player in the co-pilot seat did not have access to the ACRE radio racks like what is possible in the other H-60 variants. 

### **Expected Behavior**

At the very least whoever is not on flight controls should have access to the FLIR and be able to use the full screen view of the FLIR. 
Both seats should have a way to reference which weapon system is selected. 
Radio racks should be accessible from both seats. 

### **Video**

- [Youtube link from stream roughly around when we started getting the DAP ready](https://youtu.be/uGm6HQK6Ekc?t=1888)

**Comment by ZHANGTIANYAO1** [comment]
same issue
