### ISSUE TITLE
Help Menu locked in place and no ammo count

### ISSUE THREAD

**Issue by JackMenta** [Project-Hatchet/public_h-60#315]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer

- [X] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [X] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

https://gist.github.com/JackMenta/26d73f093fb76f2a4c472173d40aa6b5

# Bug Report

## **Description:**

You are not able to remove the Turn on AFM on the screen while seated in the GAU-21
asweel as not being able to check the ammo count as you can with the small miniguns.

### **Expected Behavior**

Should be able to disable the menu overlay.
and
Should be able to get a ammo count.

### Steps to Reproduce the Issue

1. Place down the the H-60 with GAU-21 attacment 
2. Get in the Gau gun

### **Video**

- [[Youtube link]](https://youtu.be/2lLxjHCJczA)

**Comment by FireStone1029** [comment]
should of been fixed with removal of gau-21
