### ISSUE TITLE
Co-pilot camera showing bad behaviours.

### ISSUE THREAD

**Issue by JackMenta** [Project-Hatchet/public_h-60#317]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [X] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

https://gist.github.com/JackMenta/26d73f093fb76f2a4c472173d40aa6b5

# Bug Report

## **Description:**

A couple of problems.
1. After being in a Geo-lock view, the camera will snap back to where it was looking before it snapped to the ground target.
2. 0.4%zoom will not be able to show after you have zoomed in. and sometimes the zoom will lock up unless you moved the camera at the same time.
3. 1.2%zoom will be sitting and vibrating between 1.2% and 1.3% zoom.

### **Expected Behavior**

1. Geolock should only move from the acording to where the camera is pointing and not snapping somewhere else.
2. Zoom not locking up.
3. 0.4% zoom either not be avalible or always be available.
4. 1.2% zoom should only be 1.2% zoom

### Steps to Reproduce the Issue

1. Sit in copilot seat
2. go into camera view
3. use the functions metioned.

### **Video**

- [Youtube link](https://youtu.be/npMS2DNpd3Y)

### **Additional context**

All these problems was achevied on a multiplayer server.

**Comment by Dasher112** [comment]
Also having same issues, also on a headless server.

Seat: Copilot

**Comment by YannikH** [comment]
Should be fixed in 0.6
