### ISSUE TITLE
Bug: ACRE rack not accessible from co-pilot seat

### ISSUE THREAD

**Issue by sevn10** [Project-Hatchet/public_h-60#318]
# **RPT log file:**

https://pastebin.com/TVECHURj

# Bug Report

## **Description:**
ACRE radio rack is no longer accessible from co-pilot seat in any of the H-60's. This occurs both with the Steam version and the last test version. Further, when a co-pilot does get in, radio rack functionality is broken in other vehicles. 

### **Expected Behavior**
Racks should be accessible from either seat and not effect other vehicles in the same mission.

**Comment by BroBeansCPG** [comment]
When you say other vehicles…? Is this other h-60’s or other mods too? 

Does this happen in singleplayer too or only in multicrew?

**Comment by sevn10** [comment]
All H-60 variants and vanilla vehicles. Seems to be anything that's a turret seat loses the rack. 

Only multiplayer, I don't believe ACRE can function even to test in SP.
