### ISSUE TITLE
Fix the MH-60S GAU-21

### ISSUE THREAD

**Issue by YannikH** [Project-Hatchet/public_h-60#32]
- [ ] Remove the right side GAU-21 in the model
- [ ] Add the ability to hide the doorguns
- [ ] Hide the doorgun(s) on the GAU-21 variant
- [ ] Remove the variant with both the GAU-21 and Pylons
- [ ] Re-align the GAU-21 position to be more centered in the cabin and further out of the door
- [ ] Fix up the GAU-21 positioning with animation in the viewgunner LOD
- [ ] Fix the gun smoke and muzzle flash

**Comment by ampersand38** [comment]
FIxed in 0.4.0.1 htofix
