### ISSUE TITLE
Update uh-60M documentation

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [Project-Hatchet/public_h-60#326]
## **Describe feature request.**

There are a lot of features that are not covered in the wiki. Please update the documentation.

**Comment by Riverman02** [comment]
Documentation will be updated as features become more fleshed out and can remain relatively unchanged. The mod is undergoing a lot of maintenance under the hood so a lot of features are still very fluid right now. Therefore documentation would not remain relevant very long.
