### ISSUE TITLE
Feature request:Multilingual support

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [Project-Hatchet/public_h-60#327]
Hi, could you please add native multilingual support (stringtable.xml), so we can contribute translation to this awesome mod? Thanks!

**Comment by PDTFawks** [comment]
Can you specify what you would like multilingual support for? There are stringtable.xml present in the mod already.

**Comment by ZHANGTIANYAO1** [comment]
String tables are used to make internationalization easier for the game. They are used in addons, missions, and scripts, and are located in the root of the mission or addon folders.

Any strings that are used in the game can be kept separate from the code, and can therefore easily be edited and expanded into different languages. Instead of using strings directly in the code, you are using a variable. This variable will then contain the actual string, read from stringtable.xml, with the language that is being read depending on the game settings.
https://community.bistudio.com/wiki/Stringtable.xml
Something like this

**Comment by ZHANGTIANYAO1** [comment]
Oh, I see that
