### ISSUE TITLE
Bug: Flight possible in IDLE

### ISSUE THREAD

**Issue by fire-391** [Project-Hatchet/public_h-60#333]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

[arma3_x64_2022-04-01_16-51-34.txt](https://github.com/Project-Hatchet/H-60/files/8400888/arma3_x64_2022-04-01_16-51-34.txt)

# Bug Report

## **Description:**
It is possible to fly in ENG IDLE state, in fact it flys better. Seems that there arent any weight calculations done, as flying around with full pylons and full cabin, heli handles like it is very light and no TQ is calculated so is impossible to break engines.

### **Expected Behavior**
Trying to lift off in idle should be catastrophic to the transmission. 

### Steps to Reproduce the Issue

1. Place heli in editor 
2. Fill cabin full of passengers
3. Start Engines to idle state 
4. Try to fly 

### **Screenshots**

![20220401181627_1](https://user-images.githubusercontent.com/36144022/161348240-cdc32b80-016d-4520-9527-eae889d1806b.jpg)

### **Video**

N/A

### **Additional context**
N/A

**Comment by Kill3rCat** [comment]
Are you in SFM? Using AFM, pretty sure the helicopter can take off on idle, but immediately has rpm issues and drops back down to earth, as you'd expect.

Edit: Nope, I misremembered. It gives RPM warnings but still flies fine.

**Comment by Riverman02** [comment]
IVHMS shows they are in AFM. Also you can only go to IDLE in AFM. In SFM, the PCLs are either Off or at Fly.

**Comment by SGTdanny50567** [comment]
I had this as well while using AFM, I was going off audio cues and didn't realise I didn't set them to fly. I only realised after I landed and started to shutdown

**Comment by Kill3rCat** [comment]
Yep, you're right

**Comment by BroBeansCPG** [comment]
fixed in SFM in 0.5.2

Still broken in AFM

**Comment by YannikH** [comment]
Should be fixed in 0.6
