### ISSUE TITLE
Bug: AGM-114 Hellfires will sometimes fail to track and/or get stuck in midair

### ISSUE THREAD

**Issue by Kill3rCat** [Project-Hatchet/public_h-60#334]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [X] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file: **
[arma3_x64_2022-04-01_12-07-46.txt](https://github.com/Project-Hatchet/H-60/files/8401353/arma3_x64_2022-04-01_12-07-46.txt)

# Bug Report

## **Description:**

Only tested with remote designation (not self designation). H-60 Pack AGM-114N Hellfire missiles will sometimes fail to track and will also sometimes get frozen mid-flight. AGM-114Ks seem to work as expected.

### **Expected Behavior**

Missile acquires designated target, and steers towards it, successfully tracking the target until impact.

### Steps to Reproduce the Issue

1. Equip AGM-114Ns
2. Remote designate target
3. Fire AGM-114N in LOAL-HI mode
4. Missile will likely fail to acquire the target and fly off, or get stuck in mid-air.

### **Screenshots**

![20220401141657_1](https://user-images.githubusercontent.com/63873193/161355327-35501275-dd8e-432c-9680-ea1ac22add67.jpg)

### **Additional context**

Remote designation
Using ACE3

**Comment by FireStone1029** [comment]
Going to add onto this that the Dap also has access to the L witch is a bug

**Comment by BroBeansCPG** [comment]
Original issue with ACE missiles, outside of scope.
