### ISSUE TITLE
Bug: Locality issues

### ISSUE THREAD

**Issue by FireStone1029** [Project-Hatchet/public_h-60#337]
1. locality issue where if the copilot gets in and out of the bird while the APU is on, the APU will turn off [MP] Copilot can not start the aircraft

2.If the aircraft is at FLY, and the APU is turned off, if the pilot gets out, a glitch can occur where the pilot that exits no longer sees the rotors spinning but the copilot, if inside when the pilot

3. Copilot can not start the aircraft

**Comment by Dicky-James** [comment]
Add:
   4. Swapping controls shuts off engine.
   5. Co-pilot interaction with flight levers while Pilot is flying shuts off engines.

**Comment by BroBeansCPG** [comment]
Fixed in 0.5.2
