### ISSUE TITLE
Bug: engine shut down after pilot return to helicopter 

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [Project-Hatchet/public_h-60#339]
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
# Bug Report

## **Description:**
After the pilot double-clicked V to disembark, the helicopter's engines were running normally. But the engines were shut down after the pilot re-boarded the helicopter.

### **Expected Behavior**
The engines should operate normally after the pilot returns to the helicopter

### Steps to Reproduce the Issue
1. Place a H-60 helicopter
2. Start helicopter
3. pilot double-clicked V to disembark
4.  pilot re-boarded the helicopter
5.  engines shut down

**Comment by ZHANGTIANYAO1** [comment]
In arma3 I believe that double-click V means leaving the vehicle without shutting down its engines, and single-click V means that leave the vehicle and shutting down its engines.

**Comment by Kill3rCat** [comment]
The aircraft's engines also turn off if the piloting player then unit switches / remote controls another unit and then returns to controlling the pilot unit.

**Comment by Riverman02** [comment]
Fixed in 0.5.2
