### ISSUE TITLE
Bug: The co-pilot's acceptance of control will cause the propeller to stop rotating.

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [Project-Hatchet/public_h-60#348]
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  
# Bug Report

## **Description:**
During normal flight, if the copilot receives control of the helicopter it will cause the propeller to stop spinning even though the engine 
 on the MFD appears normal.

### **Expected Behavior**
The co-pilot took control and was able to fly normally

### Steps to Reproduce the Issue
1. The main pilot launched the Heli and took off
2. The co-pilot took control

**Comment by Dicky-James** [comment]
I have had the helicopter completely shut off as well and not just appear turned off as you experienced.

**Comment by Riverman02** [comment]
Fixed in 0.5.2
