### ISSUE TITLE
Crash to Desktop MH60 DAP

### ISSUE THREAD

**Issue by Maxxx524** [Project-Hatchet/public_h-60#356]
**RPT files with client crash report**
https://drive.google.com/file/d/1J6uXtvaIXtNfoLDDyohr0fxVi4cLdQp6/view?usp=sharing 

 
 

**All mods are being used at their latest release provided on steam.**

 ace	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE TFAR BETA Setter	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2308314429
BackpackOnChest - Redux	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2372036642
BloodLust	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=667953829
Boxloader - ACE compatability	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1201499127
BoxLoader - Vehicle in Vehicle loading	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1199318917
Breaching Charge	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1314910827
CBA_A3	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CH View Distance	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=837729515
Ctab Devastator Edition	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2189592034
CUP ACE3 Compatibility Addon - Terrains	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1375890861
CUP ACE3 Compatibility Addon - Vehicles	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=621650475
CUP ACE3 Compatibility Addon - Weapons	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=549676314
CUP Terrains - Core	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
CUP Terrains - CWA	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=853743366
CUP Terrains - Maps	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=583544987
CUP Units	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=497661914
CUP Vehicles	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=541888371
CUP Weapons	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=497660133
Enhanced Map Ace Version	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2467590475
Enhanced Movement	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Enhanced Movement Rework	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2034363662
Fallujah	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=908733096
GreenMag	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2352603233
Grenades In Tank Hatches for ACE	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2398240266
Gruppe Adler Trenches	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1224892496
Hatchet Framework - Development Version	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1745501106
Hatchet H-60 pack - Development Version	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1745501605
ILBE Assault Pack - Rewrite	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1875281645
Interiors for CUP	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1883956552
ITC Addons - Rover LAD	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2083463981
Jester Mod	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2005095553
Project SFX: Remastered	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2129532219
Sling Load Rigging	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2128676112
Switchblade Loitering Munition	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2797736391
Task Force Arrowhead Radio (BETA!!!)	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=894678801
vurtual's backpack gear	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1637206746
A3 Thermal Improvement - http://steamcommunity.com/sharedfiles/filedetails/?id=2041057379
Dyna Sound 2    -    https://steamcommunity.com/sharedfiles/filedetails/?id=825181638
Enhanced Soundscape    -    http://steamcommunity.com/sharedfiles/filedetails/?id=825179978
Vehicle Inventory System    -    http://steamcommunity.com/sharedfiles/filedetails/?id=2161671937
Zeus Enhanced    -    http://steamcommunity.com/sharedfiles/filedetails/?id=1779063631
Zeus Enhanced - ACE3 Compatibility    -    http://steamcommunity.com/sharedfiles/filedetails/?id=2018593688 

## **Operating Environment** 
not sure where mission was pulled. Is liberation
**Map**  
- Fallujah	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=908733096

**Mission:**
- [x] Zeus
- [x] Downloaded
    - KP Liberation (map is Fallujah)
- [ ] Self Made
    - [Mission Name](https://steamcommunity.com/app/107410/workshop/)
- [ ] Editor

**Server Type**
- [x] Dedicated server box
    - Provider: GTXGAming
    - Operating System: ??
    - CPU: 5.2Ghz+ (16 Cores\32 Threads) (OC Extreme Performance)
    - Ram: Up to 12GB

- [ ] Locally Hosted 
    - [ ] /(optional) MP  
    - Number of Players:
    - Server Frames:
    - Server branch:
    - Provider:
    - Operating System:
    - CPU: 
    - Ram:

### Individual Things
- Did you edit anything within the mission files
 - [ ] yes
 - [ ] No
 - [x] I did not, but my server/mission guy might have.
**If yes, what did you edit exactly?**

# Bug Report

## **Description:**
flying stationary in the air, CTRL + Right Mouse into the camera. Laser on, then switch to vanilla APKWS, lock then fire. I can do this and switch in and out of the camera for a bit. There is a point/line of which once I cross it when I come out of the camera and press the F key again to switch munition, the game will visibly chug and then crash to desktop.

My first troubleshooting step was to restart the server to ensure there was no issues that were coming from the server being on for an extended period of time. I reproduced this 3 times in a row.

### **Expected Behavior**

You should crash to desktop once you press the F key to switch munitions after firing APKWS several times.

### Steps to Reproduce the Issue

1. CTRL + Right Mouse into the camera.
2. Laser on, then switch to vanilla APKWS,
3. Lock missiles and fire multiple times.
4. eventually try to switch to another munition (i had AGM - 114L x4 loaded)

**Comment by Maxxx524** [comment]
After playing around to try and figure out the issue. I believe that it has to do with the L model Hellfires in the [H60] mod. I'm not CTD with the ACE version loaded and to be entirely honest didn't know there was a pre-existing issue around those missiles.

**Comment by BroBeansCPG** [comment]
Was this reproduced consistently? 

And if so can you try reproduce it with only the core mods loaded? 

The AGM-114L is an issue (fixed in next vers) but it shouldn’t cause a CTD

**Comment by Maxxx524** [comment]
Yes, i was able to log in yesterday afterwards to do more verifying and was able to reproduce it at assembly line speeds. I have a recording of it that i will upload later if necessary. 

As far as core mods. I dont know if it can be reproduced with a reduced mod count yet.

**Comment by BroBeansCPG** [comment]
If you can please upload that, that’d be a big help. 

And also if you can try with a reduced mod count even better

**Comment by Maxxx524** [comment]
Here is a video of the crash. there is no audio, it isn't necessary and I forgot to program the audio during the recording.

https://youtu.be/2SGEvQ812y4

**Comment by PDTFawks** [comment]
Can you upload the missionfile you're testing on? I am unable to recreate the issue so far.

**Comment by Maxxx524** [comment]
https://drive.google.com/file/d/1HM4NXiqv6wkD6YC6I5y5vHLJQbyEwoi8/view?usp=sharing

Let me know if this does not work.

**Comment by PDTFawks** [comment]
I'm unable to recreate the issue on the missionfile with the mods you mentioned.

**Comment by Maxxx524** [comment]
That is interesting. I will talk to my guys and will see about investigating it on our end. If you cant recreate it. Then that points fingers at our server. Next time i will attempt to do it again on my machine alone, and not on our server to see what happens. If it doesn’t happen on my machine alone, ill post here the result and tell my guys whats up.
