### ISSUE TITLE
Bug: MicroDAGR Fuckery.

### ISSUE THREAD

**Issue by kiel2000** [Project-Hatchet/public_h-60#362]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [Y] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

# Bug Report

## **Description:**
Copilot importing DAGR waypoints, gives neither waypoints on HMD. Further, Copilots MFD is stuck on "accept" page. 
When the pilot imports his waypoints, that "unlocks" both pilots waypoints in their respective HMDs (of which the copilots is #ffffff for reasons...). Yup, respective. That means, that to my knowledge there currently is no way of having the copilot.. yanno, navigate for the pilot that is yanno.. flying. 
 
### **Expected Behavior**
Not that. Jokes aside, if copilot uploads waypoints to the helicopters navigation system, we need both pilots to see that. Also green HMD nice, but that's a different story.

### Steps to Reproduce the Issue

1. copilot goto HMD
2. copilot goto Nav page 
3. copilot MDAGR import
4. copilot Accept
5. pilot Look at HMD 

### **Video**

- [Youtube link](https:/youtube.com)

**Comment by FireStone1029** [comment]
Are you and your co pilot in the same group?

**Comment by kiel2000** [comment]
.. good question.

Not 1h ago, but last training i do believe so.

I’ll double check as soon as one of the flight is available, and let you
know.

Kielbasa
