### ISSUE TITLE
Bug: flir tracking / unstowing erros

### ISSUE THREAD

**Issue by FireStone1029** [Project-Hatchet/public_h-60#369]
flir has issues tracking vics and the unstow time seems to not like to be 20 seconds

**Comment by TheBlackFox27** [comment]
I've seen the counter go up every time I started another helicopter up after dying. I think it was once up to 10 minutes I would have had to wait. Not sure though, if it is related to deaths or not because I couldn't reproduce it yet, but it has happend multiple times.

**Comment by BroBeansCPG** [comment]
> 

any chance you have a RPT either from the server or your client at that time the number went up?

**Comment by TheBlackFox27** [comment]
Unfortunately no, since I don‘t know what a RPT is and since I haven‘t gotten that issue anymore so far.

**Comment by TheBlackFox27** [comment]
![20221027220442_1](https://user-images.githubusercontent.com/72557971/198387648-59dcd09d-86ce-4ed4-8ff5-0005be3e7621.jpg)
I don't know if I'm supposed to be uploading images here but there you go. I crashed before this screenshot and in it I am in a new helicopter and it's gone up to 50, as you can see. So if I crash one or a couple more times it will steadily (or rather exponentially is a better way to describe it)
 go up. (If you would kindly tell me how to upload an RPT, I would gladly do so)

**Comment by BroBeansCPG** [comment]
%appdata%\local\arma 3

**Comment by BroBeansCPG** [comment]
Related to cbaMissionTime? Somehow?

**Comment by TheBlackFox27** [comment]
Update: Might be connected with air vehicle kills. Crashing a friendly aircraft (with passengers) counts as friendly fire and a helicopter kill, therefore makes you a hostile to friendly AI. Same goes here.
I started a scenario, was messing around with zeus, switched a friendly vanilla uh80's group side to independent, then shot it down with an igla. Afterwards got into MH-60M DAP MLASS from this mod and unstowing now takes 50 seconds.
I can send the rpt in a moment.

**Comment by TheBlackFox27** [comment]
https://pastebin.com/x8fudP3S
not sure if I did this correctly but here you go. That's the part of the rpt file where I presume the startup starts. Before that it was repeating "Trying to call remoteExec(Call) with a null-object as JIP ID" constantly, so I didn't include that
