### ISSUE TITLE
Code Error in Uh60_cas/functions/UpdateOverlayList.sqf

### ISSUE THREAD

**Issue by Xavia1991** [Project-Hatchet/public_h-60#370]
There is an error in the script at line 18 where it says ammoOnPylon 3.
as i was not sure what the right wording  would be I could not fix this myself.
`if (_canOpen || _vehicle ammoOnPylon 3 > 0) then {`

error ingame

![image](https://user-images.githubusercontent.com/5678451/195712915-e41ad2bf-52f8-4514-9881-5d8a80fec36f.png)

**Comment by PDTFawks** [comment]
Please include your RPT log if possible.
Can you give some more information about when/how it happened? And does it happen when using only the required mods?

**Comment by Xavia1991** [comment]
I don't know exactly when this script is used, but if you take a look at the script you ll see there is an obvious mistake there.
it should probably be either ammoOnPylon_3 or ammoOnPylon3 but is ammoOnPylon 3 with a space.

**Comment by PDTFawks** [comment]
No, it is correct. `ammoOnPylon` is a command, not a variable.
What are you doing when this error is happening?

**Comment by Xavia1991** [comment]
I'll have to clarify this with our pilots as I am the tech guy who is only involved in infantry and we just had a first training with this mod.

Anyways I d check for a syntax problem maybe you ll have to put ammoOnPylon 3 in braces.

**Comment by Xavia1991** [comment]
RPT File error:

`
20:56:41 Error in expression <


if (_canOpen || _vehicle ammoOnPylon 3 > 0) then {


[_vehicle, 3, 1 + vtx_uh60_c>


20:56:41   Error position: <> 0) then {


[_vehicle, 3, 1 + vtx_uh60_c>


20:56:41   Error >: Type Bool, expected Number,Not a Number


20:56:41 File z\vtx\addons\uh60_cas\functions\fnc_updateOverlayList.sqf..., line 18
`

**Comment by Xavia1991** [comment]
Was likely an error on our side that I was not aware of.
