### ISSUE TITLE
Model: Error on loading the mission

### ISSUE THREAD

**Issue by Maxsword** [Project-Hatchet/public_h-60#374]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [X] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# Model Error report 

 **Description:**
While loading map an error shows up."No entry'bin\config.bin/CfgVehicles/vtx_H60_base/Turrets/CopilotTurret/MFD/VTX_H60_HDTS_Copilot.Bones'. The error does not prevent keep loading the mission and playing it, but it is annoying.
- text
### **Expected Behavior**

- text

### **Screenshots**

- text
### **Video**

- [Youtube link](https:/youtube.com)

### **Additional context**

- text 

[ Error .pdf](https://github.com/Project-Hatchet/H-60/files/9900481/Error.pdf)

**Comment by BroBeansCPG** [comment]
do you have a client .rpt? or what mods are you running?

**Comment by Maxsword** [comment]
yes there you go.
``
[arma3_x64_2022-10-30_18-48-57.zip](https://github.com/Project-Hatchet/H-60/files/9900904/arma3_x64_2022-10-30_18-48-57.zip)
