### ISSUE TITLE
Loading boxes then unloading them dose not unlock the seats 

### ISSUE THREAD

**Issue by FireStone1029** [Project-Hatchet/public_h-60#385]

**Comment by BroBeansCPG** [comment]
Is there more info on this? How are you unloading? Are you interacting with the box and dragging/carrying it out or are you unloading cargo via the heli interact?

**Comment by FireStone1029** [comment]
use are ace interaction viv then unloading via the same wont unlock the seats

**Comment by BroBeansCPG** [comment]
kinda fixed, need to look at fixing for dragging/carrying them out. 

Further, unloading often clips under the front landing gear, unsure if mempoint or luck but looking into it
