### ISSUE TITLE
Bug: ai not engaging heli with iglas? 

### ISSUE THREAD

**Issue by FireStone1029** [Project-Hatchet/public_h-60#387]

**Comment by manganap** [comment]
I did some testing with this and it seems to specifically be an interaction between the Hatchet helicopters and the RHS AFRF Igla. The AI will engage vanilla and RHS AFRF helicopters but will not use the Igla on Hatchet models.

If the AI has a rifle, they will use that to shoot at the helicopters but if you remove the AI's rifle they will repeatedly equip and unequip the Igla launcher. I have used Zeus to take control of the MANPAD and I was able to fire the missile so there does not seem to be anything physically preventing the use of the launcher.

**Comment by BroBeansCPG** [comment]
Just to confirm, vanilla AI targets it correct?

**Comment by manganap** [comment]
The AI will engage the Hatchet helicopters with the vanilla Titan MPRL

**Comment by manganap** [comment]
Further testing, this seems to apply to the RHS USAF Stinger manpad as well.

**Comment by BroBeansCPG** [comment]
Thanks, tracking. We’ve got it narrowed down

**Comment by Holgerhollebolle** [comment]
I just made an issue that is maybe the same. Actually AI does not attack with any AA Guns as well. We tested a lot of vehicles and turrents. HMGs seem to work...but most vehicles with AA capability wont attack. Only with rockets but not with Guns.
https://github.com/Project-Hatchet/H-60/issues/425

**Comment by Holgerhollebolle** [comment]
Also Vanilla Tigris is not attacking with Guns...only firing Rockets and when Rockets are empty it is not firing with the Guns.

**Comment by SekiAlpha** [comment]
Most, if not all, AA assets will only be used against hatchet birds if they're radar-guided.

**Comment by SekiAlpha** [comment]
![image](https://github.com/Project-Hatchet/H-60/assets/12445848/ece9a0f8-e9eb-4688-a27d-353d7a33bae4)

**Comment by Riverman02** [comment]
Fixed in #472
