### ISSUE TITLE
Bug: I can't interact with buttons while using free-cursor

### ISSUE THREAD

**Issue by deBearN** [Project-Hatchet/public_h-60#389]
I don't have the **RIGHT WINDOWS KEY** so i changed my free-cursor button to **CTRL**, while trying to use the free-cursor i can use Scroll Wheel to interact with the levers, but i can't use neither F or Alt+F to interact with the buttons (i can't use CTRL-Q CTRL-E either but is probably because i'm already using CTRL as the free-cursor key).

https://www.youtube.com/watch?v=0qEIggglLlc

while getting the .rpt i did manage to make it work by using my TeamSpeak button (RIGHT_ALT), and Primary mouse button (F and ALT+F doesn't work with this either)
here's the .rpt https://filetransfer.io/data-package/jd29fAOc#link

**Comment by YannikH** [comment]
the F and alt+F not working while using the free cursor is expected, if you can use left mouse button that works as intended
