### ISSUE TITLE
Bug: engine start up logic not functioning properly

### ISSUE THREAD

**Issue by helpingeiz** [Project-Hatchet/public_h-60#402]
# Bug Report

## **Description:**
the engine start-up for all Blackhawk models is not functioning correctly. the AIR SCE switch can be put to ENG SCE, then both throttles can be in flight setting, and then ignited and rapidly brought up to full flight speed on both engines at the same time. 

### **Expected Behavior**
normal start-up of the airframe, however AIR SCE switch set to APU with a single engine bringing that engine to idle and then flight when at the right RPM, then the other engine can be started using APU SCE setting or ENG SCE setting. 

### Steps to Reproduce the Issue
1. do normal start-up routine until SCE switch, set SCE to switch to ENG 
2. move both throttles to flight and move the fuel levers to the correct position. 
3. turn on the engine ignition switch, then ignite both engines in quick succession.  
4. continue with the rest of the normal start-up checklist and operations. 
 

### **Video**
start-up routine used. 

- [Youtube link](https://youtu.be/gRNoNxdqsI8)

### **Additional context**
this issue was present in both the single-player editor as shown in the video, as well as a hosted modded Arma 3 server. 
ACE, CTAB,ITC, all installed alongside other mods in both cases.

**Comment by BroBeansCPG** [comment]
The AIR SCE switch isn't entirely functional from memory, 

however in the video the engines started after the APU was on, which is normal behaviour, you can immediately put the PCL's at fly however it's not recommended and iirc can cause damage. We had this simulated before we may have since removed that though..
