### ISSUE TITLE
Bug: APU does not burn fuel

### ISSUE THREAD

**Issue by fire-391** [Project-Hatchet/public_h-60#412]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

https://pastebin.com/PKZSQYMu

# Bug Report

## **Description:**
APU does not burn fuel

### **Expected Behavior**
fuel burn rate should be about 3 LBS/min

### Steps to Reproduce the Issue

1. spawn helicopter
2. turn on APU

### **Screenshots**
N/A

### **Video**
N/A

### **Additional context**
N/A

**Comment by Riverman02** [comment]
Fixed. In Stable now
