### ISSUE TITLE
Feature request: Foldable rotors and tail

### ISSUE THREAD

**Issue by tspindler-cms** [Project-Hatchet/public_h-60#422]
## Support for SH-60 style for carrier use

We're still looking for a nice helo to go with the USS Nimitz mod for Arma 3 and a folding rotor and tail option would look great for use on the carrier. Example pic: https://upload.wikimedia.org/wikipedia/commons/6/6e/Seahawk_with_tail_folded.jpg

**Comment by Riverman02** [comment]
Won't happen without some substantial model work
