### ISSUE TITLE
H-60 hellfires still not guiding, at least for self lazing

### ISSUE THREAD

**Issue by marslol** [Project-Hatchet/public_h-60#43]
https://youtu.be/s5YjPMjU3ww

**Comment by A26mike** [comment]
The video is private

**Comment by marslol** [comment]
forgot to finish processing, it's updated now sorry.

**Comment by A26mike** [comment]
What helfire were you using

There are two versions one for radar locked and one for laser guided

For the radar guided it requires a radar lock. I can't remeberbif it's R or T. And I believe you still get the vannila locking noise but I can be wrong.

and what mode it LOBL or LOAL

**Comment by marslol** [comment]
First two hellfire's were H-60 114K's & other two are ACE 114K's, 2nd ones worked obviously.

ACE hellfire's do not allow you to select from the LOBL/LOAL options, only vanilla hellfire's allow for that for some reason in the DAP.

From my understanding there was a fix for the H-60 hellfire's for v0.2 but they still aren't working for me.

**Comment by YannikH** [comment]
Can't reproduce in 0.3, closing
