### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BrunoDenisov** [Project-Hatchet/public_h-60#435]
## **Describe feature request.**
Adding some kind of weapons overly when you enter to use the FLIR with your mouse, so you'd know what weapon you have selected. Also perhaps add the constraint square for the AGM-144s same as before when you enter the FLIR to control it with your mouse(CTRL + right click)

**Comment by FireStone1029** [comment]
may i suggest using the flir via the mfd over full screen?

**Comment by Riverman02** [comment]
The idea is that the full screen FLIR would be used more for observation and better situational awareness. The symbology on the MFD FLIR is visible enough that you can make the engagement from the cockpit. Also utilizing the LST feature will keep you from needing to move the camera yourself during a Hellfire engagement.

**Comment by BrunoDenisov** [comment]
Yea, the MDF is visible, no problems with that. It becomes an issues if you are not running max PIP and cannot engage up to the effective range of a hellfire.

**Comment by BrunoDenisov** [comment]
To add to this, the MDF does not have integration with A3TI, and vanilla thermals are still not the best choice.
