### ISSUE TITLE
Enable ViV cargo in no-seat variants.

### ISSUE THREAD

**Issue by YannikH** [Project-Hatchet/public_h-60#46]
Place a ViV cargo space the complete size of the whole cabin space. 

**Requirements**
Similarly to the cabin doors:

- If anybody is sitting in the cabin space, use [this](https://community.bistudio.com/wiki/enableVehicleCargo) to stop people from loading vehicles.
- If a vehicle is loaded in to the cargo, lock all of the seats in the cargo space. (potentially leave the spaces for sitting on the edge of the cabin or something like that free).

**Bonus points**

- Add an ACE interact to standard fuel crates to load them in to a nearby vehicle using ViV cargo, so ammo crates can be internally carried and not just slingloaded.

**How to configure ViV:**
https://community.bistudio.com/wiki/Arma_3:_Vehicle_in_Vehicle_Transport

**example image:**
![image](https://user-images.githubusercontent.com/4272044/107950249-c244d300-6f96-11eb-98bf-363f9b6d8fba.png)

**Comment by ampersand38** [comment]
Potential inspiration for interactions https://steamcommunity.com/sharedfiles/filedetails/?id=1199318917
I think an ACE interaction conditional to a vehicle being cargo to unload it would be good. For loading, maybe we can have an interaction on the bird to temporarily enable loading, one of:
- what the player is looking at
- nearby objects
