### ISSUE TITLE
Add Firemode to HMD

### ISSUE THREAD

**Issue by ampersand38** [Project-Hatchet/public_h-60#52]
**Is your feature request related to a problem? Please describe.**
HMD does not display firemode, and vanilla HUD is hidden. Can't tell rocket salvo size, gun RoF, hellfire mode.

**Describe the solution you'd like**
Display firemode next to weapon name in lower left.

**Describe alternatives you've considered**
FMS or MFD page

**Comment by FatLurch** [comment]
I haven't had any luck finding a documented source to display this information. 

Does anyone have a hint other than developing a dedicated function and using userText?

**Comment by PhantomDevTeam** [comment]
Try messing with the "weaponState" command. It returns an array with the muzzle firemode as an element.
https://community.bistudio.com/wiki/weaponState

**Comment by FatLurch** [comment]
Thanks, I've been playing with that a bit - I'm not getting "pretty" names for a lot of the H-60 weapons.

Examples:
```
["vtx_hellfire_launcher","vtx_hellfire_launcher","vtx_hellfire_launcher","VTX_4Rnd_ACE_Hellfire_AGM114K",4,0,0]
["vtx_MH60M_M134_minigun","vtx_MH60M_M134_minigun","HighROF","5000Rnd_762x51_Belt",5000,0,0]
["missiles_DAR","missiles_DAR","Far_AI","VTX_PylonRack_M261_M229",19,0,0]
```

**Comment by PhantomDevTeam** [comment]
A possibility would be to take the first element (the weapon class) and do a CfgWeapons search for it's display name. That should get a good display name for it. For getting a pretty firemode name, I'm not sure on that. I can do some messing around and see if I can come up with anything for it

**Comment by BroBeansCPG** [comment]
Would need to use a userText tho to display anything from a function 

Does the vanilla Ah-6m display fire rate modes for the miniguns? 

We can easy add magazine and weapon names in the mfd config but it doesn’t have a firemode option

**Comment by PhantomDevTeam** [comment]
It kinda does. It uses the segmented bar to display the fire rate. 
3 lines = low, 5 lines = high.

Looking at how Kimi's HMD works, he's defined display names for each firemode. I'm still working out how he's actually displaying them but I'm 100% sure he's using that for it.

**Comment by FatLurch** [comment]
Ampersand, were you partially wanting this in place so you can hide the ACE Hellfire overlay?

I've got the code figured out for getting the details from the ACE overlay:
```
//Get attack mode
_myText = (uiNamespace getVariable ["ace_laser_display", displayNull]) displayCtrl 1001;
ctrlText _myText;

//Get laser code
_myText = (uiNamespace getVariable ["ace_laser_display", displayNull]) displayCtrl 1002;
ctrlText _myText;

//Get lock status 
_ctrlIcon = (uiNamespace getVariable ["ace_laser_display", displayNull]) displayCtrl 1003;
ctrlTextColor _ctrlIcon select 0;
```

Also, ROF and salvo size is currently moot - they're not in the mod. Were there plans to add multiple modes in the future?
I've got "single" and "ripple" modes working for the Hydras - I can add that in with this if that's what you were looking for.

**Comment by FatLurch** [comment]
[https://www.youtube.com/watch?v=_Kfj5zEzbTg](https://www.youtube.com/watch?v=_Kfj5zEzbTg)

**Comment by YannikH** [comment]
Implemented in FLIR in 06
