### ISSUE TITLE
Uh-60M turrets occasionally delete players model

### ISSUE THREAD

**Issue by allegedflora** [Project-Hatchet/public_h-60#66]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

([Server RPT](https://gist.github.com/SirGhosty22/15fa0c411b34f8cf9c6c490c650b09f4)

# Bug Report

## **Description:**

When dismounting from UH-60M turrets, players get "Deleted" for lack of a better word, they go invisable and cannot interact with the world until respawn

### **Expected Behavior**

Players dismount with a funtioning body and the ability to be seen

### Steps to Reproduce the Issue

1. Get in UH-60m turret
2. Dismount

### **Video**

- [Video showing what happened](https://www.youtube.com/watch?v=tYTMiWNxO58&feature=youtu.be )

### **Additional context**

N/A

**Comment by YannikH** [comment]
What is the repro rate like? I can't repro it on singleplayer but I think I witnessed it in mp the other day

**Comment by BroBeansCPG** [comment]
Just repro’d first shot in SP, however I was running a lot of extra mods. 

Will test further maybe tomorrow

**Comment by allegedflora** [comment]
So far ive only seen it happen a couple times, this is with my units modlist loaded though, unsure if it has to do with a mod conflict or is an error with the blackhawk

**Comment by allegedflora** [comment]
https://youtu.be/UDHTiGLysMw <Video is still processing but I got it to constantly reproduce
