### ISSUE TITLE
Feature Request: MedEvac “Dustoff” model

### ISSUE THREAD

**Issue by ThomasM365** [Project-Hatchet/public_h-60#70]
It would be incredible if you guys add a model that represents a modern US Army MedEvac helicopter. Similar to the green one that is already there plus the red and white cross medical insignias. 

No seats in the back, a rescue hook, and maybe the option to have door guns or not. Also no fuel probe (just a standard UH-60 that’s dressed up).

Refer to the RHS “UH-60M MEV” model for the insignias and where they go.

I love flying MedEvac missions in your original H-60 but the addition of a Dustoff model will hit closer to home for me. 

Thank you!

**Comment by A26mike** [comment]
Thank you for the Idea, we will revisit it in the future.
