### ISSUE TITLE
Requests for Keybinds

### ISSUE THREAD

**Issue by ampersand38** [Project-Hatchet/public_h-60#71]
Some frequently-used functions and interactions can be prioritized for being made into CBA keybinds. Feel free to request here.

**Comment by fire-391** [comment]
Interior panel lights

**Comment by BroBeansCPG** [comment]
Declutter Mode - understand this one may be difficult because of the Imp/Metric systems

**Comment by ampersand38** [comment]
> Declutter Mode - understand this one may be difficult because of the Imp/Metric systems

There is a CBA setting for the Default HMD Mode. Do you really feel you need to change HMD modes with a keybind?

**Comment by BroBeansCPG** [comment]
Button/Knob interaction (allow reassignment from scroll wheel)

**Comment by zeidlos** [comment]
Next/Prev Waypoint

**Comment by kiel2000** [comment]
anti-collision lights (green'n'red + flashing )

**Comment by BroBeansCPG** [comment]
> anti-collision lights (green'n'red + flashing )

A vanilla keybind exists for this. I think ctrl + L or alt + L by default
