### ISSUE TITLE
Bug: 360 Spinning after engine shuts down?

### ISSUE THREAD

**Issue by Oyu07** [Project-Hatchet/public_h-60#73]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [ ] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

# Bug Report

## **Description:**

Happened during online OP. Pilot: It suddenly started stalling so I went full collective. Engines went out and started spinning rapidly, upside down etc.

### **Expected Behavior**

It would stall and not 360 spin?

### Steps to Reproduce the Issue

1: 0 idea

### **Video**

https://streamable.com/i18ob8

### **Additional context**

There were some additional problems with that helicopter. This was a scripted "Hearts and Minds" operation. Co-pilot WAS functional at first but after a while co-pilot became unable to interact with anything. No interactable cockpit. Not sure if this can give a hint but just putting it here.
*Michael said to make a bug report*

**Comment by SekiAlpha** [comment]
Where you using the advanced flight model and is there more context to that video?

Another thing to note if that if the helicopter engine is stalling you want to lower your collective to relieve torque on your engine so it can recover and spool back up.

**Comment by Oyu07** [comment]
> Where you using the advanced flight model and is there more context to that video?
> 
> Another thing to note if that if the helicopter engine is stalling you want to lower your collective to relieve torque on your engine so it can recover and spool back up.

1: I wasn't the pilot but I WAS on the helicopter, sitting at the side.
2: YES, We did have Advanced Flight model on. That pop up normally shouldn't appear but yet it did. 

Again, this was a scripted mission in which you can *respawn* complete wreck helis/vehicles so I guess they could have caused an issue, but yeah, it was on advanced.

Edit: Said pilot sent a longer vid from his POV. https://streamable.com/of0r4n

**Comment by SekiAlpha** [comment]
Well in that case it kind of looked like the helicopter descent rate was very high, to counter-act it I think the pilot increased collective all the way up. However, it over-torqued the main rotor and broke it. Though the helicopter spinning after the main rotor breaking is weird.
