### ISSUE TITLE
Bug: Basic Flight Model Max Speed

### ISSUE THREAD

**Issue by SekiAlpha** [Project-Hatchet/public_h-60#74]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [✔] I checked the documentation and found no answer
- [✔] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [✔] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT FILE**

- https://hatebin.com/kuybjnocmd

# Bug Report
Max speed on the basic flight model is too high.

## **Description:**

While flying the helicopter in the basic flight model you can get up to speeds of 180 knots.

### **Expected Behavior**

Max expected speed is 140 knots.

### Steps to Reproduce the Issue

1. Get in the UH-60.
2. Fly forward at a level attitude.
3. Take note of the max speed.

### **Screenshots**

The video should suffice

### **Video**

- [Youtube link](https://youtu.be/nEIteYGgdOs)

### **Additional context**

I'd like to say I would love to help work on the flight model be I have no idea what tools to use to even start tweaking it.

**Comment by ampersand38** [comment]
I see some sources saying the -60 can exceed airframe max safe speed 193 kts in level flight, plus a lot of other sources saying "max speed" well over 140. Why do you think 140 is the max speed?

**Comment by SekiAlpha** [comment]
> 
> 
> I see some sources saying the -60 can exceed airframe max safe speed 193 knots in level flight, plus a lot of other sources saying "max speed" well over 140. Why do you think 140 is the max speed?

Ah yes, my bad I was mainly doing this off memory. IIRC the 140knots speed is around about the cruise speed. However, the max speed currently on the hatchet mod UH-60 is beyond even the CH-47 max speed (around 310kph or 167 knots).

However, one thing to note is what exactly is the difference between max speed and cruise speed? Is cruise speed obtained by measuring level flight? What if maximum speed is measured with nonlevel flight, meaning that the helicopter started at a higher altitude? 

Either way, I'd love to see your sources of the max airspeed being 193 knots. But again I find it quite hard to believe since as far as I know the CH-47 is the fastest helicopter in the US arsenal with a top speed of 310kph or 167knots. But since my sources aren't that good (Wikipedia) I'm inclined to believe you.

**Comment by PDTFawks** [comment]
According to Boeing the H-47 Chinook's maximum speed to 302 KM/H (170 KTAS) and its cruse speed it 291 KM/H (157 KTAS).
https://www.boeing.com/defense/ch-47-chinook/

Lockheed Martin's pamphlet on the UH-60 (A/L/M) states that the UH-60M's cruse speed is 279KM/H (151 KTS), I wasn't able to find documentation on it's maximum speed.
https://lockheedmartin.com/content/dam/lockheed-martin/rms/documents/black-hawk/sikorsky-UH60M-BLACKHAWK-sellsheet.pdf
(above link downloads the UH-60 sell sheet PDF)

**Comment by BroBeansCPG** [comment]
I believe cruise speed is based on an efficiency calculation, range and stress imposed on the airframe and powertrain would definitely come into consideration

@PDTFawks beat me too it. The cruise speed according to LM is 151 knots, safe to say maximum speed would be beyond that.

**Comment by Xovolovo** [comment]
The speed problem in SFM is something their aware of. The normal flight speed for the uh-60 is around 120 knots.

**Comment by BroBeansCPG** [comment]
Source? 

And normal flight speed aka cruise speed =/= maximum speed
