### ISSUE TITLE
Bug: Co pilot not able to fire the Hell fires while in the FLIR pod. 

### ISSUE THREAD

**Issue by DontayP** [Project-Hatchet/public_h-60#88]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**

- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

# Bug Report

### Steps to Reproduce the Issue

1. Text goes here 
2. Text goes here 
3. Text goes here 
4. Text goes here 
5. Text goes here 

### **Video**

- [Youtube link](https:/youtube.com)

**Comment by A26mike** [comment]
![image](https://user-images.githubusercontent.com/36065925/108963733-7eae3100-7648-11eb-8158-6894e48951a1.png)

**Comment by A26mike** [comment]
Follow the template , as best as you can
