### ISSUE TITLE
Fms Ammo Text for miniguns bugged on pylon variants

### ISSUE THREAD

**Issue by FireStone1029** [Project-Hatchet/public_h-60#90]
Prerequisites
Please answer the following questions for yourself before submitting an issue.

- [x]  I checked the documentation and found no answer
- [ ]  I checked to make sure that this issue has not already been filed
- [ ]  I checked the FAQ and known bugs on the discord

**RPT log file:**

**Bug Report**

**Description**:
Ammo text for the miniguns on the fms are bugged on pylon variants

**Expected Behavior**

**Steps to Reproduce the Issue**
Get in bird
turn on batt and gen
go to mission system tab
then ammo tab

**Screenshots**
![image](https://user-images.githubusercontent.com/34311095/108800629-abd3e400-7561-11eb-981b-53cab9ed1e70.png)

![image](https://user-images.githubusercontent.com/34311095/108892090-7967cc80-75dd-11eb-8be7-873fa92ef984.png)

**Comment by ampersand38** [comment]
#89 fixes hoist strings. This should stay open for FMS.

**Comment by ampersand38** [comment]
FIxed in 0.4.0.1 htofix
