### ISSUE TITLE
MH-60_Rapid rappelling system and Fulton surface-to-air recovery system

### ISSUE THREAD

**Issue by JaysonLLL** [Project-Hatchet/public_h-60#92]
[rav_lifter_a3.zip](https://github.com/Project-Hatchet/public_h-60/files/6031577/rav_lifter_a3.zip)
I hope MH-60 can have its own fast abseiling system.This is a product "RAV_lifter" from the transfer of arma2 to Arma3.It is very suitable as a reference.ACE's abseiling is not real enough.I think Skyhook is also a very important case of MH-60.

**Comment by BroBeansCPG** [comment]
Please improve the format of your feature request and include images of your comparison. 

Yes ACE isn’t perfect but I’ve never seen a better system.

**Comment by A26mike** [comment]
The Skyhook has not been in use since I cant remember but maybe around the 60, while it was an cool. ACE fast roping is fine for this
