### ISSUE TITLE
Bug: Copilot can't fire weapons while in FLIR

### ISSUE THREAD

**Issue by ampersand38** [Project-Hatchet/public_h-60#93]

**Comment by Mcnabicus** [comment]
i just want to add to this. i have been doing some testing on a dedi sever yesterday, and this is just an idea regarding this issue. it seems that the co-pilot camera is a Target Camera. Should this not be classed as a turret? rationale behind this if you look at the vanilla drones, the comanche gunners position they all right click mouse and go into a turret and not the target camera. maybe the case for multi crewing this needs to be coded as a turret. the reason i came to this conclusion is that within the unit i am currently in we use two mods for multi-crewing airframes. 1 = https://steamcommunity.com/sharedfiles/filedetails/?id=1623498241 this allows us to slew to grid and too map if the camera is in a geolock postion. and also https://steamcommunity.com/sharedfiles/filedetails/?id=2041057379&searchtext=A3TI To enhance the thermal imaging. and as you can see these are based on turret configurations. Now these two mods have no effect on the flir camera position in the co- pilots seat which made me come to this conclusion. These two mods work on all of cup, rhs & vanilla assets. As i stated this is just an idea. Hope it helps.

**Comment by BroBeansCPG** [comment]
The FLIR system is entirely unique in the terms of it doesn’t share a lot of core back end workings with any other vehicle (to my knowledge) in Arma.

For the FLIR to be functional from both seats Yax had to work some magic and in the process found that it wouldn’t work if classed as a turret (correct me if I’m wrong)

A3TI compatibility will therefor not work out of the box as of yet (but is planned) and some functions we intend to take inspiration from Turrets Enhanced. 

See #91

**Comment by YannikH** [comment]
This issue is likely caused due to being inside a camera causing the fire button to be disabled. To fix this we should listen on a mouse click event, and emit a fire command manually to the current weapon on the user's current seat.
