### ISSUE TITLE
Variants with pylons should be heavier and slower than those without

### ISSUE THREAD

**Issue by ampersand38** [Project-Hatchet/public_h-60#94]

**Comment by YannikH** [comment]
I suggest we write a central detectWeight function in uh60_misc.
This function will calculate weight based on:

- Current components on the helicopter (animation based, are crew seats here? do we have pylons? how about FLIR?)
- Current munitions on your pylons
- Content loaded in to ViV crates inside the helicopter
- Possibly even equipment carried in the backpacks of infantry carried in the back?
- Equipment loaded in to the helicopter inventory itself also?

This function can be run on any getIn, getOut, fired, and ViV loaded/unloaded eventhandler which can then run setCustomWeightRTD
https://community.bistudio.com/wiki/setCustomWeightRTD

This will give us a very realistic cargo loading capacity.
