### ISSUE TITLE
Bug: H-60 Suspension

### ISSUE THREAD

**Issue by fire-391** [Project-Hatchet/public_h-60#95]
# Prerequisites

- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [x ] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord

# **RPT log file:**

https://pastebin.com/EXipK3Lb

# Bug Report

## **Description:**
Suspension is still bottomed out on AFM causing a bounce when exiting vehicle or changing flight model.

### **Expected Behavior**
Should not move at all or very little

### Steps to Reproduce the Issue

1. spawn '60' in editor
2. switch between AFM and SFM or get in out

### **Screenshots**
N/A

### **Video**
https://youtu.be/AYcOQ8cLtM0

### **Additional context**
Only tested on MH-60M, video is not from RPT session however behavior was reproduced.

**Comment by A26mike** [comment]
Great Video, The Suspension is still a WIP we are aware of thank you for the great videl
