### ISSUE TITLE
Bug: Doorgunner's body are off centered

### ISSUE THREAD

**Issue by Rios92** [Project-Hatchet/public_h-60#96]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [X] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# **RPT log file:**
[doorgunner_seat.zip](https://github.com/Project-Hatchet/public_h-60/files/6047755/doorgunner_seat.zip)

# Bug Report

## **Description:**
Character moves off centered from the left side of the seat when in the right gun. Character moves off centered either side based on the direction of the gun pointing. I reinstalled the mod and still received the problem

### **Expected Behavior**
Character moves off centered from the left side of the seat when in the right gun. Character moves off centered either side based on the direction of the gun pointing

### Steps to Reproduce the Issue
1A. Get in Right Gunner Seat
2A. Be in 1st Person and look down
3A. Off Centered from the left side of the Seat
4A. Move the gun around
5A. Stayed off centered from the left side of the seat

1B. Get in Left Gunner Seat
2B. Be in 1st Person and Look Down
3B. Centered to the seat
4B. Move the gun from front to back
5B. Go to 3rd Person and view yourself after moving the gun
6B. Off Centered from the seat based on the direction of the gun it's aimed

### **Screenshots**
Attached to file named doorgunner_seat.zip

### **Video**
N/A

### **Additional context**
I reported the problem to Ampersand (member of the same unit we're in) of the issue and he told me to  report it here

**Comment by ampersand38** [comment]
Left gun pointing forward
![image](https://user-images.githubusercontent.com/11483210/110817582-7108c600-825a-11eb-9032-fb0cc9867cc7.png)


Left gun pointing rear
![image](https://user-images.githubusercontent.com/11483210/110817520-62baaa00-825a-11eb-9372-d33795dbf9f7.png)

**Right gun pointing forward**
![image](https://user-images.githubusercontent.com/11483210/110817732-9269b200-825a-11eb-8e3e-79eee8947527.png)

Right gun pointing rear
![image](https://user-images.githubusercontent.com/11483210/110817694-87af1d00-825a-11eb-9df7-f2e85ab78453.png)

I wonder if the gunner animation is the same on both sides and therefore it's stuck on the wrong phase of it on the right.

**Comment by ampersand38** [comment]
Fixed in turn out in 0.4.0.1 htofix
