### ISSUE TITLE
Ground troops can send JVMF messages

### ISSUE THREAD

**Issue by YannikH** [Project-Hatchet/public_h-60#98]
## **Is your feature request related to a problem? Please describe.**
The JVMF system currently isn't very good.

## **Describe the solution you'd like**
- Ground troops can send JVMF messages
- Ground troops can send positions using JVMF
- Ground troops can send 5-line CAS requests using JVFM
- Ground troops can send 9-line Medevac requests using JVMF

## **Describe alternatives you've considered**

N/A

## **Additional context**

- Consider updating the JVMF system to be CBA event based so we can emit events that allows you to hook ACK functionality in to missions.

**Comment by sevn10** [comment]
I'm not sure what would be used in ACE for this, but if it could tie into the messaging system from ctab that would be excellent.

**Comment by BroBeansCPG** [comment]
Initial release will be our own tablet GUI

I don’t have time to explore the CTAB side of things. Someone is more than welcome to see if they can talk together

**Comment by sevn10** [comment]
Understood, I was just thinking in terms of reducing the amount of tablets people need to grab. That's why ctab still is so prevalent in milsim communities. I can poke around in ctab and see what I can dig up.

**Comment by YannikH** [comment]
Done
