### ISSUE TITLE
Allow players to move between copilot seat and crew seats

### ISSUE THREAD

**Issue by YannikH** [Project-Hatchet/public_h-60#99]
## **Is your feature request related to a problem? Please describe.**
- Most arma communities will only have up to 2 players crewing an H-60, we'd like to be able to have both a crew chief and a copilot.

## **Describe the solution you'd like**
- Add a funcitonality, either through an ACE interact or an in-vehicle interaction point to switch between the gunner seats and the copilot seat.

## **Describe alternatives you've considered**
- Ask people to use Ride Where You Look

## **Additional context**
N/A

**Comment by ampersand38** [comment]
closed by #204
